---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster }}-external-dns
  namespace: argocd
  labels:
    cluster: {{ .Values.cluster }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-dns
    name: {{ .Values.cluster }}
  project: default
  syncPolicy:
    automated: {}
    syncOptions: 
    - CreateNamespace=true
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '6.5.3'
    chart: external-dns
    helm:
      releaseName: external-dns
      values: |
{{ .Files.Get "values-external-dns.yaml" | indent 8 }}