---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  name: tier1-gw-customer360
  namespace: default
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: demo-apps
    tsb.tetrate.io/workspace: customer360
spec:
  displayName: Tier 1 Gateway
  description: Tier 1 Gateway
  namespaceSelector:
    names:
      - "*/demo-microservices-tier1"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  name: customerportal-gw-01
  namespace: default
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: demo-apps
    tsb.tetrate.io/workspace: customer360
spec:
  displayName: Customer Portal Gateway 01
  description: Customer Portal Gateway 01
  namespaceSelector:
    names:
      - "gke-east/demo-microservices"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  name: customerportal-gw-02
  namespace: default
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: demo-apps
    tsb.tetrate.io/workspace: customer360
spec:
  displayName: Customer Portal Gateway 02
  description: Customer Portal Gateway 02
  namespaceSelector:
    names:
      - "gke-west/demo-microservices"
  configMode: BRIDGED