image:
  registry: gcr.io/abz-perm
  tag: 1.5.1
operator:
  deployment:
    env:
    - name: CONTROL_PLANE_REVISION
      value: tsb-1-5-0-stable
spec:
  components:
    gitops:
      enabled: true
      reconcileInterval: 60s
    internalCertProvider:
      certManager:
        managed: EXTERNAL
    xcp:
      revision: tsb-1-5-0-stable
      centralAuthMode: JWT
    rateLimitServer:
      backend:
        redis:
          uri: ratelimit-redis.default.svc.cluster.local:6379
    oap:
      kubeSpec:
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: oap-deployment
          patches:
          - path: spec.template.spec.containers.[name:oap].env[-1]
            value:
              name: SW_STREAMING_LOG_ENABLED
              value: "true"
  hub: gcr.io/abz-perm
  managementPlane:
    clusterName: gke-east
    host: tsb.tetrate.cloud.zwickey.net
    port: 443
    selfSigned: false
  meshExpansion: {}
  telemetryStore:
    elastic:
      host: elastic.tetrate.cloud.zwickey.net
      port: 9200
      protocol: https
      selfSigned: false
      version: 7
secrets:
  keep: false
  clusterServiceAccount:
    JWK: '{"alg":"RS256","d":"F6FOxE4N01eedYFAwY6c18nt1eeRlkbDRVA0lRjWLRTmdIi-AE7MOxhURS6hEsKVm9dQ40ahdZ_K5Wt6L15_RtXDf_YaTLh7HXbHH2F7p9hycYS1823cBXbpRfmxvpekqrmOZ3Wi93EtU_Ona4WseSIVEJz4RvXGIbXPGRtah2X6JYxt8ONsdFa_vxcZa4iagfwomYLnbd9-byYs4H-ebk2MU1NSPVJ4jij3Wjes7VofK5ut57p3p-BmL0qb0IfHx3MSBOfalSO1MGxq11gJxMC6K7mzGN6YxDVli19uk5qyUr75sqN5EcgX4qd5ybAK-4OfSBYkg2rFD5CVNNNOwQ","dp":"B8FZaQM5gTqB17Xso13xSpEO2EZwl_lG7XxrbRwyDY61Rrt-CmHJY-oxhHbPVgRjAfGB6Itvka4O7pCMHbawqc58Xdzl79dMPyb9uCbQ-34JU457c1zJ423s7lzcQyVAVyzGbnxdqr0T-mpB2VSbbV6mZvft6yIYSoiJDqGswNs","dq":"SeRLU8hfU7f1fuiPbx1daueXZrK_JtyRzhPLw_H2N4II6IrkoRLKOkwqThYIsLepwYW96GZ_gdlQjcY1WTeX7RWdTXTKfFaICor5LOrDVHTGIVC7zB5o-sylUeZpKlrDgajvdhXgcDIBw9Lnt-B2dug-ebzgLuTvI1SFXC0P9fU","e":"AQAB","kid":"1rz4gu7J95xb3iOKChzr19pI59EYuiZTAdn4AvDU2Cg","kty":"RSA","n":"sCSGVhhJpj566Hb7MKp2_Dy6WKyX0EH3f_wYYUsaB0-JAon5RnzBKVzsl_XuzY8JCe1FBoIeLEt8xi8KzE6xp6FDBSvbvmRkVj4YZ6zt3pOEXdmMswIUmG1x0QhgrZR6IQaOH1TcRnfemyp-Op2zGGqiNDzSsPoXgwbHXT87esezwJs55nNsi9ovZHaSH5Uc11FZuN90mrameo6yrkpRV5hbB9SQD4HUuOdabd1eKSZV26MbA0XiGBAHGAgiJAAbbDg_JGN0FO_vazfg5ZyVW0rozvcJrGhSeDo8-C_LSUUNo2c83WjxwQSS9exupEQBiAwhs8wC79MdjT_wx6cEww","p":"1O1bTndQl29UpEc_82g1P9mK0Gmf81S3C9WgtrWWcR7elgO6tF82IMXrDMwtj8oOnv8E1OxiyZXj98sXus30r12lTlGzgSa5zRU4pFxaw7qXY9O1H-DRXuTnr4q8-Iw5h8mwxaK2AqdiE8JA8qSZXJAdxh8yab9gDdD7TIvI7n8","q":"08Y_HoafiD-aJ_HrmUg0ILOBvnzNVmPYk-20kGRsKWzJxA8PNr_D9hXh0hTJdE-DbvMhX9iueC2dF3ZhDkMSZrjE-tcPAMLvQLsLuFmnWQ8Kq4ULcJeYTSzh_eoosRtZJuLCcv1JElqXRGvTp0qeoOeqfbbqwptjrG93hCnqj70","qi":"zlRCmHPqDOcqCG-bnHgTFUVVBM8HNHemiD76rwIwyFMVwdfnazaM4tcgBDg4W9RsQugnnhQUVpieq6mQJpXLge0dzv5kPV8GcwlTf9LG6GWuVFm-Xuddz3wi-OcHuZQ5MBiUzTRcv5X9NuroYhH7DWHGrjZIpO0hazc7-zwTH0Y"}'
    clusterFQN: organizations/tetrate/clusters/gke-east
  elasticsearch:
    username: elastic
  tsb:
    cacert: |
      -----BEGIN CERTIFICATE-----
      MIIFOzCCBCOgAwIBAgISBHy/pDMLifxfxn29DHGwLc2PMA0GCSqGSIb3DQEBCwUA
      MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
      EwJSMzAeFw0yMjA1MDUxMjM0NDRaFw0yMjA4MDMxMjM0NDNaMCYxJDAiBgNVBAMM
      GyoudGV0cmF0ZS5jbG91ZC56d2lja2V5Lm5ldDCCASIwDQYJKoZIhvcNAQEBBQAD
      ggEPADCCAQoCggEBALhnFhmt8Ylcmgx7ohO4LE3VNW7t4h9HiBBzMel82w3C9sRX
      SII/JqYDBonJIzZf5jYtZC0P3/7ZXf+NAh34q/kW6hAfB3VYamXsUY9fxMAlb1xv
      cXxGGjB6k09Yh+imR/VMfymjlUTa5uh1g/49AwltySZWGB/RAzcBGpyzOfoHCx4i
      khAAUxpEJ5cqNEGvEhR4MnRFkmRHmp6bq2GJTy4BNx1yVc980MzDYQonFOs1eiYT
      JfsQi4Wih7x+pi7+kS05MIYUzWZ0CqmoOBp4kOZpxwKz9XtWRJDaIuUR4eS/ln7H
      qbi/lJ8WLw9VE70fUV6JtBdHBRavvtve/6DpP9ECAwEAAaOCAlUwggJRMA4GA1Ud
      DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
      AQH/BAIwADAdBgNVHQ4EFgQU+odXlGDQVyhKIP/Jd6/nbh7STl0wHwYDVR0jBBgw
      FoAUFC6zF7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUF
      BzABhhVodHRwOi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9y
      My5pLmxlbmNyLm9yZy8wJgYDVR0RBB8wHYIbKi50ZXRyYXRlLmNsb3VkLnp3aWNr
      ZXkubmV0MEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYI
      KwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBAwYKKwYBBAHW
      eQIEAgSB9ASB8QDvAHUARqVV63X6kSAwtaKJafTzfREsQXS+/Um4havy/HD+bUcA
      AAGAlG4WzQAABAMARjBEAiA2iDCifW4xwq/eNDhYH1HR8cC/CmH6AITTeb3U91/3
      GQIgCyzZ+uS3hWbBvtRlEod+jDm9sJcBEfHSQhorA+dvuNwAdgBvU3asMfAxGdiZ
      AKRRFf93FRwR2QLBACkGjbIImjfZEwAAAYCUbhgVAAAEAwBHMEUCIFh0sKPU3W1D
      eOew1dSk6cnfZH/tAJz3gTCCHE7LKPPcAiEAz5wc384sEGrIXpKaKByuvH9M6H5Q
      N4Rpd5Kbxj+tBwEwDQYJKoZIhvcNAQELBQADggEBAAqUOGE39jk8uohaOt7VM/9v
      nTVaQLXg2Y7ZWAqcPFiyfYlwSO1z+al4LZSnnFGRB7RtEY0EctC7PrWj6aBvAnYg
      HRNimq85rzm8MNDoqA3E9kSYkEt5EOA9Rc4RH3+XFBEnf5x3KYCLVvh2HF6xI1PX
      TN0NkQ/VLM3n0hxD4Q60ZKCv9n1dzrJwSpfI8vGWWbG+mQUgN6W60lYGchBnAs3j
      TpJezIX5GOrSFNodXrRvj0xwvvWGEsE9kZz+OiyGPWvhFhRkglnKRJoCk1iRELaa
      4EFznCp3vcMaxHBSX4i0H0YO/RWLG4gMrKrVW69brOhp+03UxN+F03g3MqvKZYU=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
      WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
      RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
      R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
      sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
      NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
      Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
      /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
      AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
      Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
      FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
      AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
      Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
      gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
      PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
      ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
      CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
      lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
      avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
      yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
      yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
      hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
      HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
      MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
      nLRbwHOoq7hHwg==
      -----END CERTIFICATE-----
  xcp:
    rootca: |
      -----BEGIN CERTIFICATE-----
      MIIDKjCCAhKgAwIBAgIQP7a07wBIPpXK/cmmSmUxkTANBgkqhkiG9w0BAQsFADAv
      MRUwEwYDVQQKEwxjZXJ0LW1hbmFnZXIxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2Ew
      HhcNMjIwNTMxMDAwMjQzWhcNMjQxMTE2MDAwMjQzWjAvMRUwEwYDVQQKEwxjZXJ0
      LW1hbmFnZXIxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2EwggEiMA0GCSqGSIb3DQEB
      AQUAA4IBDwAwggEKAoIBAQC9uZZC/U9WetgSCt+HbDE6VmcyDVbpXxrJI/ZFUqD7
      ZTpicSnYAYofB4bVH5Ba+Y95ZPijs96RjpNmEPqs5kFT+6NxyhAjJTc5qrVBdASp
      x9C/xMOc1VwRBegx/7a9xJoBqRizRtUJrDo297wWgUhTsjVp5OVDUsRt9dgUlrvG
      2pq0kxdwamkdT5BEq9TPoOMVmEWwXGmQV6g95mBw8/VnfcO1pv7yz3kQxNzny3Bd
      ZhdVFhW5El54SiEKI1FzDM1prJFD4yeBPZ4bUqNfChjbujHniyfj4myxfMZFvb2o
      WWl5Qb983BA/khBBkxgzoNgtvBIY+9Zpq2Zhxtpa7EXRAgMBAAGjQjBAMA4GA1Ud
      DwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQuHUUghfaF+bG9
      39hWJF1de7klnzANBgkqhkiG9w0BAQsFAAOCAQEADn0jZrPAbJqdA4O8cKryITRd
      PKy+8+8E1x1765Jw+HqRHb0K+x54GnIMKDlDcexpZkrcRR7pkkeQ4Sx9MPIFSnd3
      BezfTjOcBfIzB3gj0pMbfL2kViHhEv5qM576ScJrgNHqFhHe8wCpoxP+vNDzI7jt
      wUy5zaH5h9JBXPwo6j/TSPSiUjt00d083+ACzRlWNJXYVngwOtb/t23MZ6prV/8h
      4BFF0GlpwM+1EGlOERjKgBTc+Ir9v1HZZCVtgal0aAGczFTxvOBghu7Nwfz5e5IG
      TLKxAFhox3XbRep+1d/tn6yHqU5Yp6VUEzyLZ48CZ6gDEqM7wrCLBoKJ+SchvQ==
      -----END CERTIFICATE-----
