image:
  registry: gcr.io/abz-perm
  tag: 1.5.1-internal-rc1
operator:
  deployment:
    env:
    - name: CONTROL_PLANE_REVISION
      value: tsb-1-5-0-stable
spec:
  components:
    gitops:
      enabled: true
      reconcileInterval: 60s
    internalCertProvider:
      certManager:
        managed: EXTERNAL
    xcp:
      revision: tsb-1-5-0-stable
      centralAuthMode: JWT
    rateLimitServer:
      backend:
        redis:
          uri: ratelimit-redis.default.svc.cluster.local:6379
    oap:
      kubeSpec:
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: oap-deployment
          patches:
          - path: spec.template.spec.containers.[name:oap].env[-1]
            value:
              name: SW_STREAMING_LOG_ENABLED
              value: "true"
  hub: gcr.io/abz-perm
  managementPlane:
    clusterName: gke-east
    host: tsb.tetrate.cloud.zwickey.net
    port: 443
    selfSigned: false
  meshExpansion: {}
  telemetryStore:
    elastic:
      host: 34.85.211.82
      port: 9200
      protocol: https
      selfSigned: true
      version: 7
secrets:
  keep: false
  clusterServiceAccount:
    JWK: '{"alg":"RS256","d":"tdmKErX_fko0Ce3g1al47TPaOqefDzrAh56umjI_3JLmgNoY7t9ohFoaVxgLdRQfG131EO633ynBUxQJYCgrNfTpH3KREaWx4cQNnSVl789zvBq9vHl7UBdgr4jOaSqKHVGXIncytp0uNWApY3C7MSWt6tqxDceup7tDrj4Bu2WfNMyUSVGYLX_usKQVeNuEXUCVjlyg7RB9TacDwgvRQ8mxwdHK34JyFzizt1ugQYDyR9fHUwKtluBUMwAF0bVj1ghJgeQgcczMqzF92tL3b0cRIIVUJbua8icfefdcGaL1JVtEfpt1NRg9hHPz3pk32Y5DqrzIpBpOGgNEIzV6lQ","dp":"oC6uBSvYnHhyzx3_TxPO7qk4y2E5SvnbWlhUXXyt6PcG5NX-p1nffRy_TfqvcYF6VlPCDpdr08KakvBqpnsrcJuu12zb7innVdXeElpkrUX67dqdlHLhTi-WZFPKyyNLl9gTT9YO31o82LWqnHtuP7_kHgpg0VOpLKnRqcYLpsk","dq":"priZt6SUQsyJRnH_e9yiTFkaM7BNfStLH0H6OZ3tXNl5NxOD-_MhErzD6XUnVlx5k0h7TOD2hkua_LkI37XOIYG_7WPOcRuEIG0EuiSnd9kHWFo11lwKnq1lMUDzmcfquGlvJZNVv13rLuFyJIcw1bjEn5UFDhlLIkppoUrsds8","e":"AQAB","kid":"1wNNjN80SRMmz8QuiqI7iONbM5ImpXmYDXZy5sR5DUg","kty":"RSA","n":"tqK4iM48lMkC-GSRJt34PCbOBqcnMN5z76E-NipOfvwl2UweVkUJKtKf4rI4LMi8hmydp_Egeogf59rbr1T_qsKOouyGI3OtgOhugoBB3YGGuG7rl9DcCxrhSDG8iexXtCBsCqYFacD5pJQFPVp27myUP0ILZvzH5tZMo6FMBdt4fFCWb1SNwwazxb_f335F6INjM_qA_SO3cXzicgufQa5RsMxjfR4o2cmTDjv20CN68pNvwgrzELXurClGWt37ifSw1HxsZkYggAONJMdOEUbKvE6rwU_4As2ViQffh5m1Iv_WvF1o01si4mZy_4m-9MoKikFapLiA68d-waDNxQ","p":"6jkPt8TEn2LmejxaRj_Sr46J-eN3z323mWR_D-4nMSBT3s73sP-PLQ42kvaA-NqqzXl6uW8qCKCPDbPQhIumyAr2oK5Lr7QWkkAKGX_1zvCgCrlaoOQLnMIK2hBOxSiAGQ-rDfehcc6VTHuqp_WkoWFTxJbf69QxoBsKjY7Y5As","q":"x53JdYI8yZ2urrdyX4f2k3ECv8FyeWgpKzJHbud-LpX_hojjhRFl8SU3mtWF-icqBVnEQ3YCeazSjlZQrh_gh9EgF_aW2nLq3WHXd0qBixuOqCkvjYSeTEyWpXN2fjCrlobtQUcjJndNGkOHroQJGJ9AGUNTvGbN4o1TlGVw528","qi":"EUjoFR6cZqSTJqBPBAtCS97ae4XQACeqe3_QQFGSWjWGYakZK74yAosDRxornXbPz4TIYuGtW3eaitBC6IKPabN4RbIA9XiHdLERucVi_omt8m0bHHjxix0xuUgrnBY_tW4Kzihqs3CbZPtY1h-HDUGk6cEYTCJgrlauHrgiBMc"}'
    clusterFQN: organizations/tetrate/clusters/gke-east
  elasticsearch:
    cacert: |
      -----BEGIN CERTIFICATE-----
      MIIEMzCCAxugAwIBAgIRAPI0BvDeIuvWvYHwyXFqFgMwDQYJKoZIhvcNAQELBQAw
      ITEMMAoGA1UECxMDdHNiMREwDwYDVQQDEwh0c2ItaHR0cDAeFw0yMjA3MjExNTA1
      MDRaFw0yMzA3MjExNTE1MDRaMDwxDDAKBgNVBAsTA3RzYjEsMCoGA1UEAxMjdHNi
      LWVzLWh0dHAuZWxhc3RpYy1zeXN0ZW0uZXMubG9jYWwwggEiMA0GCSqGSIb3DQEB
      AQUAA4IBDwAwggEKAoIBAQDRtF4m4sDQMFuL8jBhQ5SVT1O63TcNiEFn5Md7LfUV
      YWdR8MR3Rq34NJaBk7DUZwYNfY856kI1zbrRgMZDJtXcIiEq9/GdHMvNfT59lVGJ
      z1cstQaabVNqr1hJJYpcpbwu2fdDIYH7bVWzltr2f9c5RS4EvkipLKqa8VdSo9HA
      1Fz+OE1/7Km2554c04ofkRFN3i8RYpEWlEjOP+XUhN1TawBk2SRnVyynXRXTstjT
      lUKIhf1Lzpja2wuKJeC7AaHjyf3nfXjyXQTp5mnz9yC3OVoA3aCTSHAx7/dhQqbe
      tvMjkZqc++CDuii9bOnoNA3tIiO/gUGnXcQ6ieZ4nDJbAgMBAAGjggFJMIIBRTAO
      BgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB8G
      A1UdIwQYMBaAFLr/IB3mC71TM/WO/nVRDPHuBvb7MIHyBgNVHREEgeowgeeCI3Rz
      Yi1lcy1odHRwLmVsYXN0aWMtc3lzdGVtLmVzLmxvY2Fsggt0c2ItZXMtaHR0cIIe
      dHNiLWVzLWh0dHAuZWxhc3RpYy1zeXN0ZW0uc3Zjghp0c2ItZXMtaHR0cC5lbGFz
      dGljLXN5c3RlbYIndHNiLWVzLWludGVybmFsLWh0dHAuZWxhc3RpYy1zeXN0ZW0u
      c3ZjgiN0c2ItZXMtaW50ZXJuYWwtaHR0cC5lbGFzdGljLXN5c3RlbYIjKi50c2It
      ZXMtZGVmYXVsdC5lbGFzdGljLXN5c3RlbS5zdmOHBCJV01IwDQYJKoZIhvcNAQEL
      BQADggEBAAxT/g0+he8kVLHa8aUv+CoINV5+GaP3olq7RyXk5DJ06wyBT8sg0/uF
      boBEuELHOI8dH31YkFHoznQq/AG4r+xAKUWkh7TRZmIvrIX4Orma2yRl+2pu3yGv
      x+qimQOYeiKhlb48iHeLMdON8ehkOaY/xMANCPIBPP1Qok+CP6ChMtVOnmWVjiam
      +NplBuhkVj4ydutNNbtk8apVoLoh9eeEErOk227Ciy5eHE6hDtw0gHxUKbm7tZ1A
      UU6nnp2x17ETmhHJ7vPFQtna119IOk9s1QDty1kIPZV8ozj7nzkGACctYpySGqah
      sRAuIswndwWlpzabyzbs3J9g7hj70yg=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDLTCCAhWgAwIBAgIQbsD5pJ6DySNrEO0tL0G7qTANBgkqhkiG9w0BAQsFADAh
      MQwwCgYDVQQLEwN0c2IxETAPBgNVBAMTCHRzYi1odHRwMB4XDTIyMDcyMTE1MDQz
      MVoXDTIzMDcyMTE1MTQzMVowITEMMAoGA1UECxMDdHNiMREwDwYDVQQDEwh0c2It
      aHR0cDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANAuUtb8V55NORzw
      WW0nLmyTh6VH/sHAvrup66r1b8X97DXkI7xEhI8UrsBUrbbas8rm+5ECbrjZNysY
      jubqh6AtXfb0QM2E+K5+m4egJh267cN7I0xQ+cdYx3zag38KNPSV2MSCSTIYE/QB
      +e69Dg1tou9Lyp7fjqSpb2EubwIMzfhbMaBz9iurgluaGWgjmlhnTaMUBP8GC7Yl
      /bdEupWSP/IKzHTk0/0kiIxYtIQCEVw5rqdk/vby4U4JmpNlP9Ryge/0Y4Np4AVZ
      tXrQc1gqiNKCoz7XYDuax0PgQQptxEuvqgpdQeOYT9xBNYE/HsGcxMfNc95PfGyy
      LuAB/C0CAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKEMB0GA1UdJQQWMBQGCCsGAQUF
      BwMBBggrBgEFBQcDAjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBS6/yAd5gu9
      UzP1jv51UQzx7gb2+zANBgkqhkiG9w0BAQsFAAOCAQEAWqw07+1SXd9dh6g1oaaI
      YghCrZ6RK5Wb4+Wok7By3nUGU/a8e1NCXnscmruY4CIqtetgrCcM0cc2w416PxZ0
      DUS9YWGFN3leSJ/n0nbMxYPvepln3gfRJ3k3XnxFUj03ogfmlcLbZO3Doy0+xygW
      SjNRR4qsAtN8uC9R+cOicIpHY+UVrMmfquWSqNTrJ3aNFcWCiUVFzfAWIgqE9Wrw
      GSmzvlMl69aXaJIvF/ECtcEqsPu+TsWFEwBFHSIWACfIe0pipA6y7eKHCweEG3Rl
      SQraheACPlCIXeUvt+TSj/5w/p3QnvLM5mAgMoF5X5JnKhN4HFjIMGEs72inZg5D
      xg==
      -----END CERTIFICATE-----
    username: elastic
  tsb:
    cacert: |
      -----BEGIN CERTIFICATE-----
      MIIFOzCCBCOgAwIBAgISBHy/pDMLifxfxn29DHGwLc2PMA0GCSqGSIb3DQEBCwUA
      MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
      EwJSMzAeFw0yMjA1MDUxMjM0NDRaFw0yMjA4MDMxMjM0NDNaMCYxJDAiBgNVBAMM
      GyoudGV0cmF0ZS5jbG91ZC56d2lja2V5Lm5ldDCCASIwDQYJKoZIhvcNAQEBBQAD
      ggEPADCCAQoCggEBALhnFhmt8Ylcmgx7ohO4LE3VNW7t4h9HiBBzMel82w3C9sRX
      SII/JqYDBonJIzZf5jYtZC0P3/7ZXf+NAh34q/kW6hAfB3VYamXsUY9fxMAlb1xv
      cXxGGjB6k09Yh+imR/VMfymjlUTa5uh1g/49AwltySZWGB/RAzcBGpyzOfoHCx4i
      khAAUxpEJ5cqNEGvEhR4MnRFkmRHmp6bq2GJTy4BNx1yVc980MzDYQonFOs1eiYT
      JfsQi4Wih7x+pi7+kS05MIYUzWZ0CqmoOBp4kOZpxwKz9XtWRJDaIuUR4eS/ln7H
      qbi/lJ8WLw9VE70fUV6JtBdHBRavvtve/6DpP9ECAwEAAaOCAlUwggJRMA4GA1Ud
      DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
      AQH/BAIwADAdBgNVHQ4EFgQU+odXlGDQVyhKIP/Jd6/nbh7STl0wHwYDVR0jBBgw
      FoAUFC6zF7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUF
      BzABhhVodHRwOi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9y
      My5pLmxlbmNyLm9yZy8wJgYDVR0RBB8wHYIbKi50ZXRyYXRlLmNsb3VkLnp3aWNr
      ZXkubmV0MEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYI
      KwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBAwYKKwYBBAHW
      eQIEAgSB9ASB8QDvAHUARqVV63X6kSAwtaKJafTzfREsQXS+/Um4havy/HD+bUcA
      AAGAlG4WzQAABAMARjBEAiA2iDCifW4xwq/eNDhYH1HR8cC/CmH6AITTeb3U91/3
      GQIgCyzZ+uS3hWbBvtRlEod+jDm9sJcBEfHSQhorA+dvuNwAdgBvU3asMfAxGdiZ
      AKRRFf93FRwR2QLBACkGjbIImjfZEwAAAYCUbhgVAAAEAwBHMEUCIFh0sKPU3W1D
      eOew1dSk6cnfZH/tAJz3gTCCHE7LKPPcAiEAz5wc384sEGrIXpKaKByuvH9M6H5Q
      N4Rpd5Kbxj+tBwEwDQYJKoZIhvcNAQELBQADggEBAAqUOGE39jk8uohaOt7VM/9v
      nTVaQLXg2Y7ZWAqcPFiyfYlwSO1z+al4LZSnnFGRB7RtEY0EctC7PrWj6aBvAnYg
      HRNimq85rzm8MNDoqA3E9kSYkEt5EOA9Rc4RH3+XFBEnf5x3KYCLVvh2HF6xI1PX
      TN0NkQ/VLM3n0hxD4Q60ZKCv9n1dzrJwSpfI8vGWWbG+mQUgN6W60lYGchBnAs3j
      TpJezIX5GOrSFNodXrRvj0xwvvWGEsE9kZz+OiyGPWvhFhRkglnKRJoCk1iRELaa
      4EFznCp3vcMaxHBSX4i0H0YO/RWLG4gMrKrVW69brOhp+03UxN+F03g3MqvKZYU=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
      WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
      RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
      R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
      sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
      NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
      Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
      /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
      AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
      Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
      FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
      AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
      Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
      gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
      PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
      ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
      CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
      lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
      avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
      yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
      yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
      hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
      HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
      MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
      nLRbwHOoq7hHwg==
      -----END CERTIFICATE-----
  xcp:
    rootca: |
      -----BEGIN CERTIFICATE-----
      MIIDKjCCAhKgAwIBAgIQP7a07wBIPpXK/cmmSmUxkTANBgkqhkiG9w0BAQsFADAv
      MRUwEwYDVQQKEwxjZXJ0LW1hbmFnZXIxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2Ew
      HhcNMjIwNTMxMDAwMjQzWhcNMjQxMTE2MDAwMjQzWjAvMRUwEwYDVQQKEwxjZXJ0
      LW1hbmFnZXIxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2EwggEiMA0GCSqGSIb3DQEB
      AQUAA4IBDwAwggEKAoIBAQC9uZZC/U9WetgSCt+HbDE6VmcyDVbpXxrJI/ZFUqD7
      ZTpicSnYAYofB4bVH5Ba+Y95ZPijs96RjpNmEPqs5kFT+6NxyhAjJTc5qrVBdASp
      x9C/xMOc1VwRBegx/7a9xJoBqRizRtUJrDo297wWgUhTsjVp5OVDUsRt9dgUlrvG
      2pq0kxdwamkdT5BEq9TPoOMVmEWwXGmQV6g95mBw8/VnfcO1pv7yz3kQxNzny3Bd
      ZhdVFhW5El54SiEKI1FzDM1prJFD4yeBPZ4bUqNfChjbujHniyfj4myxfMZFvb2o
      WWl5Qb983BA/khBBkxgzoNgtvBIY+9Zpq2Zhxtpa7EXRAgMBAAGjQjBAMA4GA1Ud
      DwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQuHUUghfaF+bG9
      39hWJF1de7klnzANBgkqhkiG9w0BAQsFAAOCAQEADn0jZrPAbJqdA4O8cKryITRd
      PKy+8+8E1x1765Jw+HqRHb0K+x54GnIMKDlDcexpZkrcRR7pkkeQ4Sx9MPIFSnd3
      BezfTjOcBfIzB3gj0pMbfL2kViHhEv5qM576ScJrgNHqFhHe8wCpoxP+vNDzI7jt
      wUy5zaH5h9JBXPwo6j/TSPSiUjt00d083+ACzRlWNJXYVngwOtb/t23MZ6prV/8h
      4BFF0GlpwM+1EGlOERjKgBTc+Ir9v1HZZCVtgal0aAGczFTxvOBghu7Nwfz5e5IG
      TLKxAFhox3XbRep+1d/tn6yHqU5Yp6VUEzyLZ48CZ6gDEqM7wrCLBoKJ+SchvQ==
      -----END CERTIFICATE-----
