---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster }}-tsb-configurer
  namespace: argocd
  labels:
    cluster: {{ .Values.cluster }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    name: {{ .Values.cluster }}
  project: default
  syncPolicy:
    automated: {}
    syncOptions: 
    - CreateNamespace=true
  source:
    path: cd/apps/tsb-configurer
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      releaseName: tsb-configurer
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      parameters:
      - name: "tsb.password"
        value: {{ .Values.tsb.password }}
      values: |
{{ .Files.Get "values-tsb-configurer.yaml" | indent 8 }}
    