---
apiVersion: tsb.tetrate.io/v2
kind: Workspace
metadata:
  name: wealth-mgmt
  namespace: default
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: demo-apps
spec:
  description: Wealth Mgmt
  displayName: Wealth Mgmt
  namespaceSelector:
    names:
      - "*/demo-app"
      - "*/demo-app-tier1"
      - "*/demo-security"