---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: service-entry-wealth
  namespace: demo-app
  labels:
    istio.io/rev: tsb
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: demo-apps
    tsb.tetrate.io/workspace: wealth-mgmt
    tsb.tetrate.io/istioInternalGroup: allow-list-demo
spec:
  hosts:
  - www.google.com
  - www.tetrate.io
#   - www.httpbin.org
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
