---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: demo-se
  namespace: default
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: demo-apps
    tsb.tetrate.io/workspace: wealth-mgmt
    tsb.tetrate.io/istioInternalGroup: allow-list-demo
spec:
  hosts:
  - google.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS