---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: service-entry-cloud-map
  namespace: demo-app
  labels:
    istio.io/rev: tsb
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: demo-apps
    tsb.tetrate.io/workspace: wealth-mgmt
    tsb.tetrate.io/istioInternalGroup: allow-list-demo
spec:
  hosts:
  - "quotes-legacy.zwickey.cloudmap.internal"
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  - number: 8080
    name: http
    protocol: HTTP  
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
  - address: 192.168.43.63
  - address: 192.168.58.63
