---
apiVersion: v1
kind: Service
metadata:
  name: quotes-service
  namespace: demo-quotes
  labels:
    app: quotes
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: quotes
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes
  namespace: demo-quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes
      version: v2
  template:
    metadata:
      name: quotes
      labels:
        app: quotes
        version: v2
    spec:
      serviceAccountName: quotes-vm
      containers:
        - image: gcr.io/abz-perm/quotes:v1
          name: quotes-service
          imagePullPolicy: Always
          # resources:
          #   limits:
          #     cpu: 500m
          #     memory: 512Mi
          #   requests:
          #     cpu: 100m
          #     memory: 128Mi
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080