---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-quotes
  name: demo-quotes
  namespace: trafficgenerator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: demo-quotes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-quotes
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - "while true; do curl -v -k https://quotes.tetrate.cloud.zwickey.net/quotes/GOOG; sleep 10; done"
        image: appropriate/curl
        imagePullPolicy: Always
        name: trafficgenerator
        resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always