---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-cluster-issuer
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    email: {{ .Values.email }}
    preferredChain: "ISRG Root X1"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-issuer-account-key
    solvers:
      - selector:
          dnsZones:
            - {{ .Values.zone }}
        dns01:
          {{- if eq .Values.provider "google" }}
          cloudDNS:
            project: {{ .Values.google.project }}
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: credentials.json
          {{- end }}