{{- if eq .Values.provider "google" }}
---
kind: Secret
apiVersion: v1
metadata:
  name: clouddns-dns01-solver-svc-acct
  namespace: cert-manager
data:
  credentials.json: {{ .Values.gcpJsonCredential }}
{{- end }} 