---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: es-cert
  namespace: elastic-system
spec:
  secretName: es-cert
  issuerRef:
    name: letsencrypt-dns-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - elastic.tetrate.cloud.zwickey.net
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: tsb
  namespace: elastic-system
spec:
  version: 7.13.2
  http:
    service:
      spec:
        type: LoadBalancer
      metadata:
        annotations:
          "external-dns.alpha.kubernetes.io/hostname": "elastic.tetrate.cloud.zwickey.net."
    tls:
     certificate: 
       secretName: es-cert
  # auth:
  #   fileRealm:
  #   - SecretRef: xxx
  nodeSets:
  - name: default
    count: 3
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: tsb
  namespace: elastic-system
spec:
  version: 7.13.2
  http:
    # tls:
    #   certificate: 
    #      secretName: es-certs
    service:
      spec:
        type: LoadBalancer
  count: 1
  elasticsearchRef:
    name: tsb