---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: tsb
  namespace: elastic-system
spec:
  version: 7.13.2
  http:
    service:
      spec:
        type: LoadBalancer
  nodeSets:
  - name: default
    count: 3
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: tsb
  namespace: elastic-system
spec:
  version: 7.13.2
  http:
    # tls:
    #   certificate: 
    #      secretName: es-certs
    service:
      spec:
        type: LoadBalancer
  count: 1
  elasticsearchRef:
    name: tsb