image:
  registry: gcr.io/abz-perm
  tag: 1.5.1
operator:
  deployment:
    env:
    - name: CONTROL_PLANE_REVISION
      value: tsb-1-5-1-stable
spec:
  components:
    gitops:
      enabled: true
      reconcileInterval: 60s
    internalCertProvider:
      certManager:
        managed: EXTERNAL
    xcp:
      revision: tsb-1-5-1-stable
      centralAuthMode: JWT
    rateLimitServer:
      backend:
        redis:
          uri: ratelimit-redis.default.svc.cluster.local:6379
    oap:
      kubeSpec:
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: oap-deployment
          patches:
          - path: spec.template.spec.containers.[name:oap].env[-1]
            value:
              name: SW_STREAMING_LOG_ENABLED
              value: "true"
  hub: gcr.io/abz-perm
  managementPlane:
    clusterName: gke-west
    host: tsb.tetrate.cloud.zwickey.net
    port: 443
    selfSigned: false
  meshExpansion: {}
  telemetryStore:
    elastic:
      host: elastic.tetrate.cloud.zwickey.net
      port: 9200
      protocol: https
      selfSigned: false
      version: 7
secrets:
  keep: false
  clusterServiceAccount:
    JWK: '{"alg":"RS256","d":"hCgYkzfqZWlcLBeB-QXN91N-_DO_aegkpJKEAnTTl1--QYz5ZRlVH9oBtTsvFboK_t9Yp0AJKlcenX48BXhTMRAYK-Tro94Ci6PEDltw3UQgzIJsx5xT9soGggXjXYPWbzgJYPhoxX1ojWGyEWY57lfVUAgMqG1ye_tve1uhf1gwgy0hjLnhCrFRc2KM1lUxUx9FdVm9atom-I65f2UdMuL-PhXX6SK_NgUEPvyVS3Fj6LBFEnshnWOPx-xB0emNEwrdAAr5pHOWWkygwCI7gkgyXxcu3YH1yIWaD_TXPJ_HYz31L6KXfiG4g8DoK8CV-A_s3JBYrfVpmqx1DJczMQ","dp":"FUaQAhuESHF7HFR4VtGIzqJdF3vxdF-puSE_1_vALoGt7vnXZ9dEpUA2XU5Mg9QaF9sdFGKFF8pLK6uCRAr4AWAlCCnrSVyB1w9Utw83oVd9GnKh1IZdfjeIEmrUUe0Riaz2Wv-C7KQ06EWuFv39z4Uh3qPIRUEgkG48nGZFO7U","dq":"bTF29iYI7FMmmM-alRqYLlF_w6HluFx-0aUkbQbBJYatXfC42Wte8OXwhFFb40Do-HRXoaZgNYKJH_YTif8n0SKjhsOWOjbNWBbQ_mkI9KfmTPbmZejZY3g0T1mH221wlBd-eDtO9nhzUsh8vzP93jwoPszPv1Sas4J5eQ8-WDU","e":"AQAB","kid":"e8fjIgxg5ubuuFzFZqrZWUYRPe5z7Y7xlroxrUjj_tc","kty":"RSA","n":"0lmFrOB7Vf2o4P30c5EmiTnxCgVOp1s0uLNDPzE5IfLqltdGoszNJ9EbG_PdnHeNTshIgrfZncejqduDc7BMKK6XXi5kHe2fwMV2LJmp3ng-hpnjRqehREkGWSWkcHrHu7Lu6itlRibSTRJuWkP5_DGJrsW6mtAjX43e51e2tA9dzSTwBxY5VeY0Auy1h9oo3sJAx-O3UMISkYXv6zCf7TywBhNmmEQINLDt6pceNzwGJ0nH4Nx6L1q4uYTUK2Lqu4SD9aw3lBKvgiChHRF_14cAg-bIYIwVauhttzPOBZFZK5E27kQHuiNRUbh7ZsBAsjsl2vV3A7idQ-m2ijyGuQ","p":"7aiGxUqss3_fF4AYOrnG2NMAYtUPxAIvmHSh2SXsz_P563t09_UGhisBl-sim3NogFYWOzzCW92-5Ys7oMHpPPaMmhGw_cQDH2yB9XAJzGLk0DWYM6vJkgADOgdc15yqd2d1EWdz2sk4Q9Uq1Yw7DxhHBqkqJuUoQTlWNGYsrh0","q":"4pVz6lmPRRW48h3fVw5M9lPQFrWPj5OjKMdylzIaLvZrFJCP6I9wqYtfGvuNOrMFznw6PzlUd8IxDyzknJcSNzge4KohASa3jRBCs_pBjkj1WR1o_62C7snYMqBfGlyluU2l-ghPUeLqU9OstD4hVQlNEWUnkJETI2gkFRzkSE0","qi":"WCr4YyZ1FDA8FLfPba-8ozFJpojnFUz4c3RKsL_hWXsakLkl9HdJ56mGv4BuHRJPocCICN0cRclzdPXGUo0OnWvKx1_VGlVU26J7mUiGnkCgGcUzUPIQAW07Ii623M4_Jnax9ttz0snxk-dsuUfgP_myPku0rcsyHoCCzQDKiqc"}'
    clusterFQN: organizations/tetrate/clusters/gke-west
  elasticsearch:
    username: elastic
  tsb:
    cacert: |
      -----BEGIN CERTIFICATE-----
      MIIFOzCCBCOgAwIBAgISBHy/pDMLifxfxn29DHGwLc2PMA0GCSqGSIb3DQEBCwUA
      MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
      EwJSMzAeFw0yMjA1MDUxMjM0NDRaFw0yMjA4MDMxMjM0NDNaMCYxJDAiBgNVBAMM
      GyoudGV0cmF0ZS5jbG91ZC56d2lja2V5Lm5ldDCCASIwDQYJKoZIhvcNAQEBBQAD
      ggEPADCCAQoCggEBALhnFhmt8Ylcmgx7ohO4LE3VNW7t4h9HiBBzMel82w3C9sRX
      SII/JqYDBonJIzZf5jYtZC0P3/7ZXf+NAh34q/kW6hAfB3VYamXsUY9fxMAlb1xv
      cXxGGjB6k09Yh+imR/VMfymjlUTa5uh1g/49AwltySZWGB/RAzcBGpyzOfoHCx4i
      khAAUxpEJ5cqNEGvEhR4MnRFkmRHmp6bq2GJTy4BNx1yVc980MzDYQonFOs1eiYT
      JfsQi4Wih7x+pi7+kS05MIYUzWZ0CqmoOBp4kOZpxwKz9XtWRJDaIuUR4eS/ln7H
      qbi/lJ8WLw9VE70fUV6JtBdHBRavvtve/6DpP9ECAwEAAaOCAlUwggJRMA4GA1Ud
      DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
      AQH/BAIwADAdBgNVHQ4EFgQU+odXlGDQVyhKIP/Jd6/nbh7STl0wHwYDVR0jBBgw
      FoAUFC6zF7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUF
      BzABhhVodHRwOi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9y
      My5pLmxlbmNyLm9yZy8wJgYDVR0RBB8wHYIbKi50ZXRyYXRlLmNsb3VkLnp3aWNr
      ZXkubmV0MEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYI
      KwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBAwYKKwYBBAHW
      eQIEAgSB9ASB8QDvAHUARqVV63X6kSAwtaKJafTzfREsQXS+/Um4havy/HD+bUcA
      AAGAlG4WzQAABAMARjBEAiA2iDCifW4xwq/eNDhYH1HR8cC/CmH6AITTeb3U91/3
      GQIgCyzZ+uS3hWbBvtRlEod+jDm9sJcBEfHSQhorA+dvuNwAdgBvU3asMfAxGdiZ
      AKRRFf93FRwR2QLBACkGjbIImjfZEwAAAYCUbhgVAAAEAwBHMEUCIFh0sKPU3W1D
      eOew1dSk6cnfZH/tAJz3gTCCHE7LKPPcAiEAz5wc384sEGrIXpKaKByuvH9M6H5Q
      N4Rpd5Kbxj+tBwEwDQYJKoZIhvcNAQELBQADggEBAAqUOGE39jk8uohaOt7VM/9v
      nTVaQLXg2Y7ZWAqcPFiyfYlwSO1z+al4LZSnnFGRB7RtEY0EctC7PrWj6aBvAnYg
      HRNimq85rzm8MNDoqA3E9kSYkEt5EOA9Rc4RH3+XFBEnf5x3KYCLVvh2HF6xI1PX
      TN0NkQ/VLM3n0hxD4Q60ZKCv9n1dzrJwSpfI8vGWWbG+mQUgN6W60lYGchBnAs3j
      TpJezIX5GOrSFNodXrRvj0xwvvWGEsE9kZz+OiyGPWvhFhRkglnKRJoCk1iRELaa
      4EFznCp3vcMaxHBSX4i0H0YO/RWLG4gMrKrVW69brOhp+03UxN+F03g3MqvKZYU=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
      WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
      RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
      R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
      sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
      NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
      Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
      /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
      AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
      Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
      FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
      AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
      Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
      gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
      PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
      ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
      CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
      lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
      avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
      yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
      yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
      hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
      HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
      MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
      nLRbwHOoq7hHwg==
      -----END CERTIFICATE-----
  xcp:
    rootca: |
      -----BEGIN CERTIFICATE-----
      MIIDKjCCAhKgAwIBAgIQP7a07wBIPpXK/cmmSmUxkTANBgkqhkiG9w0BAQsFADAv
      MRUwEwYDVQQKEwxjZXJ0LW1hbmFnZXIxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2Ew
      HhcNMjIwNTMxMDAwMjQzWhcNMjQxMTE2MDAwMjQzWjAvMRUwEwYDVQQKEwxjZXJ0
      LW1hbmFnZXIxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2EwggEiMA0GCSqGSIb3DQEB
      AQUAA4IBDwAwggEKAoIBAQC9uZZC/U9WetgSCt+HbDE6VmcyDVbpXxrJI/ZFUqD7
      ZTpicSnYAYofB4bVH5Ba+Y95ZPijs96RjpNmEPqs5kFT+6NxyhAjJTc5qrVBdASp
      x9C/xMOc1VwRBegx/7a9xJoBqRizRtUJrDo297wWgUhTsjVp5OVDUsRt9dgUlrvG
      2pq0kxdwamkdT5BEq9TPoOMVmEWwXGmQV6g95mBw8/VnfcO1pv7yz3kQxNzny3Bd
      ZhdVFhW5El54SiEKI1FzDM1prJFD4yeBPZ4bUqNfChjbujHniyfj4myxfMZFvb2o
      WWl5Qb983BA/khBBkxgzoNgtvBIY+9Zpq2Zhxtpa7EXRAgMBAAGjQjBAMA4GA1Ud
      DwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQuHUUghfaF+bG9
      39hWJF1de7klnzANBgkqhkiG9w0BAQsFAAOCAQEADn0jZrPAbJqdA4O8cKryITRd
      PKy+8+8E1x1765Jw+HqRHb0K+x54GnIMKDlDcexpZkrcRR7pkkeQ4Sx9MPIFSnd3
      BezfTjOcBfIzB3gj0pMbfL2kViHhEv5qM576ScJrgNHqFhHe8wCpoxP+vNDzI7jt
      wUy5zaH5h9JBXPwo6j/TSPSiUjt00d083+ACzRlWNJXYVngwOtb/t23MZ6prV/8h
      4BFF0GlpwM+1EGlOERjKgBTc+Ir9v1HZZCVtgal0aAGczFTxvOBghu7Nwfz5e5IG
      TLKxAFhox3XbRep+1d/tn6yHqU5Yp6VUEzyLZ48CZ6gDEqM7wrCLBoKJ+SchvQ==
      -----END CERTIFICATE-----
