---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tsb-configurer
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: tsb-configurer-role
  namespace: istio-system
rules:
- apiGroups: ["*"]
  resources: ["pods","secrets","serviceaccounts"]
  verbs: ["create", "get", "watch", "list"]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tsb-configurer-rolebinding
subjects:
- kind: ServiceAccount
  name: tsb-configurer # Name is case sensitive
  namespace: istio-system
roleRef:
  kind: ClusterRole
  name: tsb-configurer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tsb-configurer-config
  namespace: istio-system
data:
  tsb-creds.yaml: |
    tsb:
      host: {{ .Values.tsb.endpointHost }}
      port: {{ .Values.tsb.endpointPort }}
      user: {{ .Values.tsb.username }}
      pwd: {{ .Values.tsb.password }}
      org: {{ .Values.tsb.org }}
    repo: {{ .Values.repo }}
    branch: {{ .Values.branch }}
    path: {{ .Values.path }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: tsb-configurer
  namespace: istio-system
spec:
  template:
    spec:
      containers:
        - name: tsb-configurer
          image: gcr.io/abz-perm/tsb-configurer:1.0
          imagePullPolicy: Always
          volumeMounts:
          - name: config-volume
            mountPath: /etc/tsb
      volumes:
        - name: config-volume
          configMap:
            name: tsb-configurer-config
      restartPolicy: Never
      serviceAccountName: tsb-configurer