repo: https://github.com/tetrateio/workshop-environment
branch: main
path: /cd/tsb
tsb:
  version: 1.0
  registry: gcr.io/changeme
  endpointHost: tsb.tetrate.io
  endpointPort: 8443
  username: admin
  password: changeme
  org: tetrate