---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: demo-app
  labels:
    app: backend
    version: v1
spec:
  ports:
  - port: 8080
    name: http-main
  - port: 80
    targetPort: 8888
    name: http-cats
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: demo-app
  labels:
    app: backend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
      - name: backend
        image: gcr.io/abz-perm/backend-demo:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 50m
            memory: 16Mi
          requests:
            cpu: 10m
            memory: 4Mi
        ports:
        - containerPort: 8080
        - containerPort: 8888
        env:
        - name: PORT
          value: "8080"
        - name: GOPACKAGENAME
          value: "example-apps/cats-and-dogs-with-service-discovery/backend"
        - name: CATS_PORTS
          value: "8888"
        - name: UDP_PORTS
          value: "9001,9002,9003"
        - name: CLUSTER
          value: gke-west
        - name: IMG
          value: "https://i.imgur.com/1uYroRF.gif"
        # - name: LATENCY
        #   value: "2"