---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster }}-addons
  namespace: argocd
  labels:
    cluster: {{ .Values.cluster }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    name: {{ .Values.cluster }}
  project: tsb-1.5
  syncPolicy:
    automated: {}
    syncOptions: 
    - CreateNamespace=true
  source:
    path: cd/clusters/1.5.cp-aws-east/addons
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    directory:
      recurse: true