---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster }}-external-dns-customization
  namespace: argocd
  labels:
    cluster: {{ .Values.cluster }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-dns
    name: {{ .Values.cluster }}
  project: tsb-1.5
  syncPolicy:
    automated: {}
    syncOptions: 
    - CreateNamespace=true
  source:
    path: cd/apps/customization-external-dns
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      releaseName: customization-external-dns
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      parameters:
      - name: "gcpJsonCredential"
        value: {{ .Values.gcpJsonCredential}}
      values: |
{{ .Files.Get "values-external-dns.yaml" | indent 8 }}  