---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
  labels:
    #istio-injection: enabled
    istio.io/rev: tsb-1-5-0-canary
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-security
