---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fortune
  name: fortune
  namespace: trafficgenerator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: fortune
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - "while true; do curl -v -k https://fortune.tetrate.cloud.zwickey.net/fortune; sleep 5; done"
        image: appropriate/curl
        imagePullPolicy: Always
        name: trafficgenerator
        resources:
          limits:
            cpu: 50m
            memory: 16Mi
          requests:
            cpu: 10m
            memory: 4Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always