apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: fortune
spec:
  replicas: 1
  serviceName: "redis"
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
      - image: redis:latest
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: fortune
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: redis
  type: ClusterIP
  selector:
    app: redis