---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  tenant: tetrate-trader
  organization: tetrate-workshop
  name: accounts-workspace
spec:
  description: Customer Accounts
  displayName: Customer Accounts
  namespaceSelector:
    names:
      - "gke-east/accounts"
---      
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  tenant: tetrate-trader
  organization: tetrate-workshop
  workspace: accounts-workspace
  name: accounts-gateway
spec:
  displayName: accounts-gateway
  description: accounts-gateway
  namespaceSelector:
    names:
      - "*/accounts"
  configMode: BRIDGED