---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookinfo-certs
  namespace: bookinfo
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    name: {{ .Values.certificate.clusterIssuer }}
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.fqdn }}