---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-customer360
  name: demo-customer360
  namespace: trafficgenerator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: demo-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - "while true; do curl -k -v -H 'X-B3-Sampled: 1' https://customer360.tetrate.cloud.zwickey.net/proxy/http/accounts-service/proxy/http/issues.demo.mesh/proxy/http/issues-backend; sleep 10; done"
        image: appropriate/curl
        imagePullPolicy: Always
        name: trafficgenerator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      # dnsPolicy: ClusterFirst
      restartPolicy: Always