---
apiVersion: v1
kind: Namespace
metadata:
  name: web
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui
  namespace: web
  labels:
    app: web
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: web
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: v1
  template:
    metadata:
      name: web
      labels:
        app: web
        version: v1
    spec:
      containers:
        - image: gcr.io/abz-perm/web-ui:v1
          name: web-ui
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          env:
          - name: TETRATE_QUOTESERVICEURL
            value: {{ .Values.web.quoteServiceUrl }}
          - name: TETRATE_ACCOUNTSERVICEURL
            value: {{ .Values.web.accountServiceUrl }}
          - name: TETRATE_PORTFOLIOSERVICEURL
            value: {{ .Values.web.portfolioServiceUrl }}
          - name: SPRING_SECURTY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI
            value: {{ .Values.oidc.issuerUri }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.web.certName}}
  namespace: web
spec:
  secretName: {{ .Values.web.certName}}
  issuerRef:
    name: {{ .Values.certificate.clusterIssuer}}
    kind: ClusterIssuer
  dnsNames:
    - web.{{ .Values.domain}}
---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: tsb-gateway-web
  namespace: web
spec:
  kubeSpec:
    service:
      type: LoadBalancer
      annotations:
        "external-dns.alpha.kubernetes.io/hostname": "web.{{ .Values.domain}}."