---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  tenant: tetrate-workshop
  organization: tetrate-workshop
  name: frontend-backend
spec:
  description: frontend-backend
  displayName: frontend-backend
  namespaceSelector:
    names:
      - "gke-east/workshop-app"
      - "gke-west/workshop-app"
      - "aws-east/workshop-app"
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  tenant: tetrate-workshop
  organization: tetrate-workshop
  workspace: frontend-backend
  name: frontend-gateway-01
spec:
  displayName: frontend-gateway-01
  description: frontend-gateway-01
  namespaceSelector:
    names:
      - "gke-east/workshop-app"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  tenant: tetrate-workshop
  organization: tetrate-workshop
  workspace: frontend-backend
  name: frontend-gateway-02
spec:
  displayName: frontend-gateway-02
  description: frontend-gateway-02
  namespaceSelector:
    names:
      - "gke-west/workshop-app"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  tenant: tetrate-workshop
  organization: tetrate-workshop
  workspace: frontend-backend
  name: frontend-gateway-03
spec:
  displayName: frontend-gateway-03
  description: frontend-gateway-03
  namespaceSelector:
    names:
      - "aws-east/workshop-app"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: frontend-gw
  tenant: tetrate-workshop
  organization: tetrate-workshop
  workspace: frontend-backend
  group: frontend-gateway-01
spec:
  workloadSelector:
    namespace: workshop-app
    labels:
      app: frontend-tsb-gateway
  http:
    - name: frontend-gateway
      port: 443
      tls:
        mode: SIMPLE
        secretName: frontend-certs
      hostname: frontend-01.tetrate.cloud.zwickey.net
      routing:
        rules:
          - route:
              host: "workshop-app/frontend.workshop-app.svc.cluster.local"
              port: 8888
    - name: backend-internal
      port: 80
      hostname: backend.tetrate.mesh
      routing:
        rules:
          - route:
              host: "workshop-app/backend.workshop-app.svc.cluster.local"
              port: 80
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: frontend-gw
  tenant: tetrate-workshop
  organization: tetrate-workshop
  workspace: frontend-backend
  group: frontend-gateway-02
spec:
  workloadSelector:
    namespace: workshop-app
    labels:
      app: frontend-tsb-gateway
  http:
    - name: frontend-gateway
      port: 443
      tls:
        mode: SIMPLE
        secretName: frontend-certs
      hostname: frontend-02.tetrate.cloud.zwickey.net
      routing:
        rules:
          - route:
              host: "workshop-app/frontend.workshop-app.svc.cluster.local"
              port: 8888
    - name: backend-internal
      port: 80
      hostname: backend.tetrate.mesh
      routing:
        rules:
          - route:
              host: "workshop-app/backend.workshop-app.svc.cluster.local"
              port: 80        
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: frontend-gw
  tenant: tetrate-workshop
  organization: tetrate-workshop
  workspace: frontend-backend
  group: frontend-gateway-03
spec:
  workloadSelector:
    namespace: workshop-app
    labels:
      app: frontend-tsb-gateway
  http:
    - name: frontend-gateway
      port: 443
      tls:
        mode: SIMPLE
        secretName: frontend-certs
      hostname: frontend-03.tetrate.cloud.zwickey.net
      routing:
        rules:
          - route:
              host: "workshop-app/frontend.workshop-app.svc.cluster.local"
              port: 8888
    - name: backend-internal
      port: 80
      hostname: backend.tetrate.mesh
      routing:
        rules:
          - route:
              host: "workshop-app/backend.workshop-app.svc.cluster.local"
              port: 80