---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  tenant: tetrate-workshop
  organization: tetrate-workshop
  name: frontend
spec:
  description: frontend-workspace
  displayName: frontend-workspace
  namespaceSelector:
    names:
      - "gke-east/frontend"
      - "gke-west/frontend"
      - "aws-east/frontend"
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  tenant: tetrate-workshop
  organization: tetrate-workshop
  workspace: frontend
  name: frontend-gateway-01
spec:
  displayName: frontend-gateway-01
  description: frontend-gateway-01
  namespaceSelector:
    names:
      - "gke-east/frontend"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  tenant: tetrate-workshop
  organization: tetrate-workshop
  workspace: frontend
  name: frontend-gateway-02
spec:
  displayName: frontend-gateway-02
  description: frontend-gateway-02
  namespaceSelector:
    names:
      - "gke-west/frontend"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  tenant: tetrate-workshop
  organization: tetrate-workshop
  workspace: frontend
  name: frontend-gateway-03
spec:
  displayName: frontend-gateway-03
  description: frontend-gateway-03
  namespaceSelector:
    names:
      - "aws-east/frontend"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: frontend-gw
  tenant: tetrate-workshop
  organization: tetrate-workshop
  workspace: frontend
  group: frontend-gateway-01
spec:
  workloadSelector:
    namespace: frontend
    labels:
      app: frontend-tsb-gateway
  http:
    - name: frontend-gateway
      port: 443
      tls:
        mode: SIMPLE
        secretName: frontend-certs
      hostname: frontend-01.tetrate.cloud.zwickey.net
      routing:
        rules:
          - route:
              host: "frontend/frontend.frontend.svc.cluster.local"
              port: 8888