---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  tenant: tetrate-workshop
  organization: tetrate-workshop
  name: marketdata
spec:
  description: marketdata
  displayName: marketdata
  namespaceSelector:
    names:
      - "aws-east/quotes"
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  tenant: tetrate-workshop
  organization: tetrate-workshop
  workspace: marketdata
  name: marketdata-gateway
spec:
  displayName: marketdata-gateway
  description: marketdata-gateway
  namespaceSelector:
    names:
      - "aws-east/quotes"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: marketdata-gw
  tenant: tetrate-workshop
  organization: tetrate-workshop
  workspace: marketdata
  group: marketdata-gateway
spec:
  workloadSelector:
    namespace: quotes
    labels:
      app: quotes-tsb-gateway
  http:
    - name: marketdata-internal
      port: 80
      hostname: quotes.tetrate.mesh
      routing:
        rules:
          - route:
              host: "quotes/quotes-service.quotes.svc.cluster.local"
              port: 8080