{{- $cluster := .Values.cluster -}}
# We only want quotes in AWS since this is where the VM(s) will live
{{- if eq $cluster "aws-east" }}
{{- range .Values.environments }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}-quotes
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: quotes-service
  namespace: {{ . }}-quotes
  labels:
    app: quotes
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: quotes
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes
  namespace: {{ . }}-quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes
      version: v2
  template:
    metadata:
      name: quotes
      labels:
        app: quotes
        version: v2
    spec:
      containers:
        - image: gcr.io/abz-perm/quotes:v1
          name: quotes-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
{{- end }}
{{- end }}