{{- $cluster := .Values.cluster -}}
# We only want quotes in AWS since this is where the VM(s) will live
{{- if eq $cluster "aws-east" }}
{{- range .Values.environments }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}-quotes
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: quotes-service
  namespace: {{ . }}-quotes
  labels:
    app: quotes
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: quotes
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes
  namespace: {{ . }}-quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes
      version: v2
  template:
    metadata:
      name: quotes
      labels:
        app: quotes
        version: v2
    spec:
      containers:
        - image: gcr.io/abz-perm/quotes:v1
          name: quotes-service
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: {{ . }}-quotes-gateway
  namespace: {{ . }}-quotes
spec:
  kubeSpec:
    service:
      type: LoadBalancer
      annotations:
        "external-dns.alpha.kubernetes.io/hostname": "quotes-{{ . }}.kubecon.cx.tetrate.info."
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: quotes
  namespace: {{ . }}-quotes
spec:
  secretName: quotes-cert
  issuerRef:
    name: letsencrypt-dns-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - quotes-{{ . }}.kubecon.cx.tetrate.info
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ . }}-quotes
  name: {{ . }}-quotes
  namespace: trafficgenerator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: {{ . }}-quotes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ . }}-quotes
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - "while true; do curl -v -k https://quotes-{{ . }}.kubecon.cx.tetrate.info/quotes/GOOG; sleep 10; done"
        image: appropriate/curl
        imagePullPolicy: Always
        name: trafficgenerator
        resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
{{- end }}
{{- end }}