image:
  registry: gcr.io/abz-perm
  tag: 1.5.0-EA2
spec:
  components:
    internalCertProvider:
      certManager:
        managed: EXTERNAL
    xcp:
      centralAuthModes:
        jwt: true
    frontEnvoy:
      port: 443
      kubeSpec:
        service:
          annotations:
            "external-dns.alpha.kubernetes.io/hostname": "tsb.tetrate.cloud.zwickey.net."
    apiServer:
      teamSyncSchedule: "*/10 * * * *"
  hub: gcr.io/abz-perm
  organization: tetrate
  dataStore:
    postgres:
      address: postgres-postgresql.postgres:5432
      name: postgres
      sslMode: disable
  telemetryStore:
    elastic:
      host: 34.85.219.28
      port: 9200
      protocol: https
      selfSigned: true
      version: 7
  identityProvider:
    sync:
      azure:
        clientId: e6ba27d2-9c19-4e6e-917a-2eb727bf3e88
        tenantId: 6a15254b-eb29-4152-ad3b-c755c8cff62f
    oidc:
      clientId: e6ba27d2-9c19-4e6e-917a-2eb727bf3e88
      scopes: ['email', 'profile']
      redirectUri: https://tsb.tetrate.cloud.zwickey.net/iam/v2/oidc/callback
      providerConfig:
        dynamic:
          configurationUri: https://login.microsoftonline.com/6a15254b-eb29-4152-ad3b-c755c8cff62f/v2.0/.well-known/openid-configuration      
secrets:
  keep: false
  postgres:
    username: tetrate
  elasticsearch:
    cacert: |
      -----BEGIN CERTIFICATE-----
      MIIEMjCCAxqgAwIBAgIQIxKUmN/EcI61TYyz20enQTANBgkqhkiG9w0BAQsFADAh
      MQwwCgYDVQQLEwN0c2IxETAPBgNVBAMTCHRzYi1odHRwMB4XDTIyMDYxMzIwMjIy
      N1oXDTIzMDYxMzIwMzIyN1owPDEMMAoGA1UECxMDdHNiMSwwKgYDVQQDEyN0c2It
      ZXMtaHR0cC5lbGFzdGljLXN5c3RlbS5lcy5sb2NhbDCCASIwDQYJKoZIhvcNAQEB
      BQADggEPADCCAQoCggEBAK+fIsOZGgE7lsbNIvnx2o+xP63cdJquAHufA6YMHiyc
      hQ2ImvWqGCfUCoaS7VbxWPK+gOhmZcRppsjTbQzkIPBksy6dLflq+uxVFuwh7FMB
      HG0zDox+1hv1OcF8Jhx3Ndpb2GDZ8OqzCT/ApoBah6tei7zVWrfSZjIuku6zXfpS
      PzuW/E1AAcjK2tsoNq9Ffm372Zy7wq+qStRDR6RK9WAQC6PzBw0r+ApFiERMJ0qR
      tBkMTLWiAjpmHmNwLxWjB8MwkMaUycxU2ENeVSz349AjAQ9/IseczuhOhjhhcFiX
      2j+9H3WFsMhB4bdbDYVp+YGriyZo3raaXKUEzZQseFkCAwEAAaOCAUkwggFFMA4G
      A1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHwYD
      VR0jBBgwFoAUMUrO9ny+VMmDYzxmzuilQ6TEAmMwgfIGA1UdEQSB6jCB54IjdHNi
      LWVzLWh0dHAuZWxhc3RpYy1zeXN0ZW0uZXMubG9jYWyCC3RzYi1lcy1odHRwgh50
      c2ItZXMtaHR0cC5lbGFzdGljLXN5c3RlbS5zdmOCGnRzYi1lcy1odHRwLmVsYXN0
      aWMtc3lzdGVtgid0c2ItZXMtaW50ZXJuYWwtaHR0cC5lbGFzdGljLXN5c3RlbS5z
      dmOCI3RzYi1lcy1pbnRlcm5hbC1odHRwLmVsYXN0aWMtc3lzdGVtgiMqLnRzYi1l
      cy1kZWZhdWx0LmVsYXN0aWMtc3lzdGVtLnN2Y4cEIlXbHDANBgkqhkiG9w0BAQsF
      AAOCAQEACMVVSrE86+vwZSySIig15Ew4DsP3WYH3awAeV5vYElDltSJa5KTCMIpJ
      88J5/WrxCpFEJE6oAWDhPuUce3ZzraYuWjAIWHXJY4iUL8V6DZBQC4K5qNUgVmqc
      HjDWdBFgxvGLYhrqi4Z0v4N50/k0PwKrWgeIEyWFzZrPl9QXb8huldUtyedvAYgJ
      T7rQhtewiFfg1+L996Prt9fCQZzZvuVDCzLOJNGlh0DBd/QAGLsqBvhokjU7VCdq
      ZFOo2v0dEzZRkOlLXhLXQWPc3pqszurzsQr7qPjifk1JGEWFM7Jxb9NUg1hngat6
      cUKUE9556yDMnlpHaGZvI95/Fsu0lA==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDLjCCAhagAwIBAgIRAL4TcaQ9cGjH2XIKnj+M6LQwDQYJKoZIhvcNAQELBQAw
      ITEMMAoGA1UECxMDdHNiMREwDwYDVQQDEwh0c2ItaHR0cDAeFw0yMjA2MTMyMDIx
      MzhaFw0yMzA2MTMyMDMxMzhaMCExDDAKBgNVBAsTA3RzYjERMA8GA1UEAxMIdHNi
      LWh0dHAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC4/QS7x8YrqAf3
      aSuBoPM0N1kFOubFWhhnOX3Gpl8BMZxLrmivnul4jGWWd69F5KQ19q8115HoYgbZ
      3w8uKJRvb4uCeDzmJ7olVj5Olz5NO/P6sxBHksvzuaw+nP1v+9Tbdk5mfLW5qhQU
      NsRNtgH12aozf4SpNxSzrh3zJgG/3uhA9nMBzVXyD0ru6/PfN6OKKJ+4ce4YSSpF
      s7dBCW1LdOOKoGbNIDA/e4Ewah7vdJ4HAKCXxuveqxYmErCS88UGJCr/6KiLwbOM
      BZvbQYMXC9fgNk2Rpih+JiYVB5rCMSe1/Q4PA5PXm4BVW7xAGVx4bMvMYm2cvNc6
      KhpD13nLAgMBAAGjYTBfMA4GA1UdDwEB/wQEAwIChDAdBgNVHSUEFjAUBggrBgEF
      BQcDAQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUMUrO9ny+
      VMmDYzxmzuilQ6TEAmMwDQYJKoZIhvcNAQELBQADggEBACLoUPN81r1pP43HgpPR
      UiT2nYhHF8+VJzkYmwdzl7mX5A0zyQamXZguABHKfnraAkzsPc8WoeE1qcWtXgf2
      TppkiImANK5ZEKUo1xaURq3QhdOJFjDOH0SfVoCDmaAE/p4iFjQ6n9DCKesydJQs
      cUo52h5A+taliEo6sQh9nXjjBwuYolmEl1mg9KegVbWvdDu9BY57SojtdOyknDKz
      FwjnduRkjNXB/lAHDHnc2HWoIbqgZ9uebkDc4f/ohH0LtwqLSVqyhEsHRvcFnHPV
      mXch9ktOmny9/jO//Y8ef3SPxwXmgsQDkLzuZGGAGbzTgy04hmWupE+pPD7X3yXg
      4l0=
      -----END CERTIFICATE-----
    username: elastic
  tsb:
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIFOzCCBCOgAwIBAgISBHy/pDMLifxfxn29DHGwLc2PMA0GCSqGSIb3DQEBCwUA
      MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
      EwJSMzAeFw0yMjA1MDUxMjM0NDRaFw0yMjA4MDMxMjM0NDNaMCYxJDAiBgNVBAMM
      GyoudGV0cmF0ZS5jbG91ZC56d2lja2V5Lm5ldDCCASIwDQYJKoZIhvcNAQEBBQAD
      ggEPADCCAQoCggEBALhnFhmt8Ylcmgx7ohO4LE3VNW7t4h9HiBBzMel82w3C9sRX
      SII/JqYDBonJIzZf5jYtZC0P3/7ZXf+NAh34q/kW6hAfB3VYamXsUY9fxMAlb1xv
      cXxGGjB6k09Yh+imR/VMfymjlUTa5uh1g/49AwltySZWGB/RAzcBGpyzOfoHCx4i
      khAAUxpEJ5cqNEGvEhR4MnRFkmRHmp6bq2GJTy4BNx1yVc980MzDYQonFOs1eiYT
      JfsQi4Wih7x+pi7+kS05MIYUzWZ0CqmoOBp4kOZpxwKz9XtWRJDaIuUR4eS/ln7H
      qbi/lJ8WLw9VE70fUV6JtBdHBRavvtve/6DpP9ECAwEAAaOCAlUwggJRMA4GA1Ud
      DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
      AQH/BAIwADAdBgNVHQ4EFgQU+odXlGDQVyhKIP/Jd6/nbh7STl0wHwYDVR0jBBgw
      FoAUFC6zF7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUF
      BzABhhVodHRwOi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9y
      My5pLmxlbmNyLm9yZy8wJgYDVR0RBB8wHYIbKi50ZXRyYXRlLmNsb3VkLnp3aWNr
      ZXkubmV0MEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYI
      KwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBAwYKKwYBBAHW
      eQIEAgSB9ASB8QDvAHUARqVV63X6kSAwtaKJafTzfREsQXS+/Um4havy/HD+bUcA
      AAGAlG4WzQAABAMARjBEAiA2iDCifW4xwq/eNDhYH1HR8cC/CmH6AITTeb3U91/3
      GQIgCyzZ+uS3hWbBvtRlEod+jDm9sJcBEfHSQhorA+dvuNwAdgBvU3asMfAxGdiZ
      AKRRFf93FRwR2QLBACkGjbIImjfZEwAAAYCUbhgVAAAEAwBHMEUCIFh0sKPU3W1D
      eOew1dSk6cnfZH/tAJz3gTCCHE7LKPPcAiEAz5wc384sEGrIXpKaKByuvH9M6H5Q
      N4Rpd5Kbxj+tBwEwDQYJKoZIhvcNAQELBQADggEBAAqUOGE39jk8uohaOt7VM/9v
      nTVaQLXg2Y7ZWAqcPFiyfYlwSO1z+al4LZSnnFGRB7RtEY0EctC7PrWj6aBvAnYg
      HRNimq85rzm8MNDoqA3E9kSYkEt5EOA9Rc4RH3+XFBEnf5x3KYCLVvh2HF6xI1PX
      TN0NkQ/VLM3n0hxD4Q60ZKCv9n1dzrJwSpfI8vGWWbG+mQUgN6W60lYGchBnAs3j
      TpJezIX5GOrSFNodXrRvj0xwvvWGEsE9kZz+OiyGPWvhFhRkglnKRJoCk1iRELaa
      4EFznCp3vcMaxHBSX4i0H0YO/RWLG4gMrKrVW69brOhp+03UxN+F03g3MqvKZYU=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
      WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
      RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
      R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
      sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
      NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
      Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
      /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
      AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
      Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
      FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
      AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
      Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
      gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
      PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
      ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
      CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
      lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
      avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
      yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
      yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
      hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
      HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
      MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
      nLRbwHOoq7hHwg==
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC4ZxYZrfGJXJoM
      e6ITuCxN1TVu7eIfR4gQczHpfNsNwvbEV0iCPyamAwaJySM2X+Y2LWQtD9/+2V3/
      jQId+Kv5FuoQHwd1WGpl7FGPX8TAJW9cb3F8RhowepNPWIfopkf1TH8po5VE2ubo
      dYP+PQMJbckmVhgf0QM3ARqcszn6BwseIpIQAFMaRCeXKjRBrxIUeDJ0RZJkR5qe
      m6thiU8uATcdclXPfNDMw2EKJxTrNXomEyX7EIuFooe8fqYu/pEtOTCGFM1mdAqp
      qDgaeJDmaccCs/V7VkSQ2iLlEeHkv5Z+x6m4v5SfFi8PVRO9H1FeibQXRwUWr77b
      3v+g6T/RAgMBAAECggEAfecUddAHm+u32lIHZUNYLIQoCWct/oFOazzblTmELq8w
      4PlfLl6DutFSA31rJ1Lu0YrIXOP74frzbOoPyfrhIB7/DKbC5uHJM3HYdfXDVhW5
      JPmKGHmcpADs1z3w/W2ar+bc48cmwW5cPdcOmeV6T1PABQa/TendMg705oyQRx6i
      jx+bXngvs5U4wToWmY0re7lB/AqECRM2D8Syt8x2HG02kpw3PtIr6Tl02YLl36Yr
      TKSzTron9ROZj5sFdhfJDmtQyHA5lemay4i75HEnvr6BdAjtPp/AfIh9xExXx1GL
      nGXWZStXDGtUp/IikDSuFz9C3WLh5OWloj/kr07MCQKBgQDpMU8RGIhq0hC0qyCP
      X40fG+sJ+f/0gIAQ4fqoER9Jusce4EzQe0tMrLPSZwVHSGzNhognHdSXnPQphK8h
      uE+ZSkZ6CFP3ov6tAHQ/A6sabb725c0Spv7zBN/3R6Vphdo/jwimHVzmlKQOYFyS
      GfWAXyGuHBjwTPeZGMeDYrMmswKBgQDKcCwQmit+iHS8sychzTqOQvT0Fkkj/DOm
      gj7kU0p2uXPciJq8uhReRBLRXRJnxdfRjfS/BOKSkreZL1/PnFVJta4THlo+Hfjh
      XhM9W+K1zi+fkkCqvdb2lA+28a9FMODn9RTZpF6GZ+S3f3r7Er3+SXcL6oKKmYyy
      pBvIRUkhawKBgQCACowglfjptnhny4LwVoX1a+3tp3DsPtaS7pIkUGp+oGkPQhfL
      bbeV3UpLoDecwV7EpzcBS3bc3NiQJ4PGHx7Ny6PRA9ufIMd4FMS/iPMdat8tUFb/
      A+T/aVDUxWlE/LMurQoRtBO7pChEoJKTwl8z4ohqwpDK+WgGjz2Vnc9C0wKBgBiY
      1pHR2bUPKXgAIKIXyKSeeBrsVki8DR6PNssRX7vbPruuEXca+PyXMt4je+gF/vok
      UHehRVJf51UCj5avPSGupI8IIhjoFWR0xMuwzXQfsGOoJplYZbUiOmKVLSGwFbO5
      cKYdNasJFp5BLBUzqsgp7wAQp3nlvFW8YO/Nk1wvAoGAQqqWEGYsb5tUSMq27ox6
      FgK+MbOU0DvRa4wpQs/cLupQpQKEDVtdNNlUB5fr52EkFEBblD5s1O4QzedlLvw8
      voFm86hbQGMrWWTKBwSfdhewTFo+3rcnI6BEbtIvNY36VHOsuj7Q6Fu0IY2fRL8R
      gN8/+mPHpb8DlJkKfFTmJOs=
      -----END PRIVATE KEY-----
  xcp:
    autoGenerateCerts: true
    central:
      additionalDNSNames:
      - tsb.tetrate.cloud.zwickey.net
    rootca: |
      -----BEGIN CERTIFICATE-----
      MIIDKjCCAhKgAwIBAgIQP7a07wBIPpXK/cmmSmUxkTANBgkqhkiG9w0BAQsFADAv
      MRUwEwYDVQQKEwxjZXJ0LW1hbmFnZXIxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2Ew
      HhcNMjIwNTMxMDAwMjQzWhcNMjQxMTE2MDAwMjQzWjAvMRUwEwYDVQQKEwxjZXJ0
      LW1hbmFnZXIxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2EwggEiMA0GCSqGSIb3DQEB
      AQUAA4IBDwAwggEKAoIBAQC9uZZC/U9WetgSCt+HbDE6VmcyDVbpXxrJI/ZFUqD7
      ZTpicSnYAYofB4bVH5Ba+Y95ZPijs96RjpNmEPqs5kFT+6NxyhAjJTc5qrVBdASp
      x9C/xMOc1VwRBegx/7a9xJoBqRizRtUJrDo297wWgUhTsjVp5OVDUsRt9dgUlrvG
      2pq0kxdwamkdT5BEq9TPoOMVmEWwXGmQV6g95mBw8/VnfcO1pv7yz3kQxNzny3Bd
      ZhdVFhW5El54SiEKI1FzDM1prJFD4yeBPZ4bUqNfChjbujHniyfj4myxfMZFvb2o
      WWl5Qb983BA/khBBkxgzoNgtvBIY+9Zpq2Zhxtpa7EXRAgMBAAGjQjBAMA4GA1Ud
      DwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQuHUUghfaF+bG9
      39hWJF1de7klnzANBgkqhkiG9w0BAQsFAAOCAQEADn0jZrPAbJqdA4O8cKryITRd
      PKy+8+8E1x1765Jw+HqRHb0K+x54GnIMKDlDcexpZkrcRR7pkkeQ4Sx9MPIFSnd3
      BezfTjOcBfIzB3gj0pMbfL2kViHhEv5qM576ScJrgNHqFhHe8wCpoxP+vNDzI7jt
      wUy5zaH5h9JBXPwo6j/TSPSiUjt00d083+ACzRlWNJXYVngwOtb/t23MZ6prV/8h
      4BFF0GlpwM+1EGlOERjKgBTc+Ir9v1HZZCVtgal0aAGczFTxvOBghu7Nwfz5e5IG
      TLKxAFhox3XbRep+1d/tn6yHqU5Yp6VUEzyLZ48CZ6gDEqM7wrCLBoKJ+SchvQ==
      -----END CERTIFICATE-----
    rootcakey: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAvbmWQv1PVnrYEgrfh2wxOlZnMg1W6V8aySP2RVKg+2U6YnEp
      2AGKHweG1R+QWvmPeWT4o7PekY6TZhD6rOZBU/ujccoQIyU3Oaq1QXQEqcfQv8TD
      nNVcEQXoMf+2vcSaAakYs0bVCaw6Nve8FoFIU7I1aeTlQ1LEbfXYFJa7xtqatJMX
      cGppHU+QRKvUz6DjFZhFsFxpkFeoPeZgcPP1Z33Dtab+8s95EMTc58twXWYXVRYV
      uRJeeEohCiNRcwzNaayRQ+MngT2eG1KjXwoY27ox54sn4+JssXzGRb29qFlpeUG/
      fNwQP5IQQZMYM6DYLbwSGPvWaatmYcbaWuxF0QIDAQABAoIBADBXqJT7LIsRlBrM
      0HYWOFjwCS10vq+KPy3/TtINIt3LxlutEAdtJP+REGcfus2jh05cTwqPW2flV2OL
      cgQ6S20V0mi9Hu2FnxO/jp3V7RZBxswGW/2LVAE2axrKWIr0HHXN23Ba3Q+w5ch5
      yWBGouJIp1mLLGvCHDEUknF0kvYw7jrfU5T+GCQhpWNB4eRLM6ErX44KTUfJHTq4
      /kX58ekqfDMw8g+wSk+F3KnPBgmRJWw2nSNO/k8ty8EAjhBmSSEW7dzVjdh7s9s9
      Le6+rFjpXqb2FAn5lW0pFoyK7emXdNQHnARs3qnxohBdM5HKqecvikQjvVpv0bCQ
      +dolds0CgYEAwcqPLL8u3/8cX9NmYAucoESDpLa8NSht9g/0w+XOOUpUj2pz4jmP
      Gg+IwMBMRlTEedRhd/rQaKweUL4+AtAtand1LtJP1SRBB7P6oJ30CnK0NHDpfMSc
      OUtwFWEDyCYWkRdC30QjchiFdEHHPPFM6rJ5VceeeL3Q7J8pkcfxsW8CgYEA+qDd
      uN00Z63g34P4V7ZPWYu5+Eo4G3pB1FZ5PQVrD1sDMeg9mB9cZRQWn+hXQwssXpzO
      KpVerfj+xj4vjPRVDbBXYSjXo2X+EcB5Lsya8ARG+1PSFNa8umqIkF5JvAsERqlG
      TH+n7+V2PBfYbaXZKumCVXzDu9uS6XsyIkb7XL8CgYBd/kxhbL1kocz2YYe3MAqg
      5Xpgas1wjxJ+lZCnb5AN05KeGQjqAfb5se0naF3Wgwjk+nDoC7wH+OufSBa1sJlG
      mXg55IIaJEJyZQY730DdzHLBOL7W6FnJpGBRzkNSUb8CUqD5v4fdsC0SjVEAqx0e
      fMBDLdYcRBzQmAZGkg8VewKBgQCZJhm2sD0oqcDC9JKZjobYciB2z2uPptp5FUpK
      dnggTv4Zzg9tWKSOA4N7vW8tQbOgMPNuZA4SAxg0LaXC3T7n+Xy7m0iByX5CfLnQ
      VijLR+HUDDlQkJOM2jKO/X7TEGxRfXi+oDcPycjBGdUf03tr1HrXIEE/FwKj96r/
      9R3+YwKBgCZjgsMOJzu5VZh8jtfZUftmidVlo4WhRO0uCasFuA6iSguTLYmJolpe
      QRN21zWOw7sgj45JLdROPRs4NN/1QaSvT9bfBuvRKrsJbBpDcCv1Tg8Uzf3h/YOC
      ilJY2plbZOUgptLKT0igtJVOkAeJV2w2xWwbG50Io/Su6mC7Pumu
      -----END RSA PRIVATE KEY-----