---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: bookinfo-gw
  group: bookinfo-gateway
  workspace: bookinfo
  tenant: tetrate-demo
  organization: tetrate-workshop
spec:
  workloadSelector:
    namespace: bookinfo
    labels:
      app: tsb-gateway
  http:
    - name: bookinfo-gw
      port: 80
      hostname: bookinfo.tetrate.cloud.zwickey.net
      tls:
        mode: DISABLED
      routing:
        rules:
          - route:
              host: "bookinfo/productpage.bookinfo.svc.cluster.local"
              port: 9080
    - name: details-gw
      port: 9080
      hostname: "details.tetrate.mesh"
      tls:
        mode: DISABLED
      routing:
        rules:
          - route:
              host: "bookinfo/details.bookinfo.svc.cluster.local"
              port: 9080
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Tier1Gateway
metadata:
  name: bookinfo-tier1
  group: bookinfo-tier1
  workspace: bookinfo
  tenant: tetrate-demo
  organization: tetrate-workshop
spec:
  workloadSelector:
    namespace: bookinfo
    labels:
      app: tsb-gateway
  externalServers:
  - hostname: bookinfo.tetrate.cloud.zwickey.net
    name: bookinfo
    port: 443
    tls:
      mode: SIMPLE
      secretName: bookinfo-certs