{{ if eq .Values.tsbGatewayDeploy true }}
---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: tsb-gateway
  namespace: bookinfo
spec:
  kubeSpec:
    service:
      type: LoadBalancer
{{- end }} 
