---
openapi: 3.0.1
info:
  title: Quotes OpenAPI definition
  version: v1
  x-tsb-service: quotes.papa-quotes
servers:
- url: https://quotes.papa.workshop.cx.tetrate.info
  description: Server url
  x-tsb-tls:
    mode: SIMPLE
    secretName: quotes-certs
- url: http://quotes.papa.mesh
  description: Server url
paths:
  /quotes/{symbols}:
    get:
      tags:
      - quote-v-1-controller
      operationId: getQuotes
      parameters:
      - name: symbols
        in: path
        required: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
  /company/{name}:
    get:
      tags:
      - quote-v-1-controller
      operationId: getCompany
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CompanyInfo'
components:
  schemas:
    Quote:
      type: object
      properties:
        symbol:
          type: string
        companyName:
          type: string
        currency:
          type: string
        latestPrice:
          type: number
        high:
          type: number
        low:
          type: number
        change:
          type: number
    CompanyInfo:
      type: object
      properties:
        symbol:
          type: string
        companyName:
          type: string
        exchange:
          type: string
