apiVersion: api.tsb.tetrate.io/v2
kind: Cluster
metadata:
  description: Cluster created via tctl
  name: gke-west
  organization: tetrate
spec:
  description: Cluster created via tctl
  fqn: organizations/tetrate/clusters/gke-west
  locality:
    region: us-west4