---
apiversion: application.tsb.tetrate.io/v2
kind: Application
metadata:
  organization: kubecon
  tenant: $PREFIX-apps
  name: marketdata
spec:
  displayName: Market Data
  description: Market Data application
  workspace: organizations/kubecon/tenants/$PREFIX-apps/workspaces/marketdata
apiVersion: gateway.tsb.tetrate.io/v2
---
apiversion: application.tsb.tetrate.io/v2
kind: API
metadata:
  organization: kubecon
  tenant: $PREFIX-apps
  application: marketdata
  name: quotes
spec:
  displayName: Quotes API
  description: Quotes API
  workloadSelector:
    namespace: $PREFIX-quotes
    labels:
      app: $PREFIX-quotes-gateway
  openapi: |
    openapi: 3.0.1
    info:
      title: Quotes OpenAPI definition
      version: v1
      x-tsb-service: quotes-service.$PREFIX-quotes
    servers:
    - url: https://quotes-$PREFIX.kubecon.cx.tetrate.info
      description: External Server url
      x-tsb-tls:
        mode: SIMPLE
        secretName: quotes-cert
    - url: http://quotes.$PREFIX.mesh
      description: Internal Server url
    paths:
      /quotes/{symbols}:
        get:
          tags:
          - quote-v-1-controller
          operationId: getQuotes
          parameters:
          - name: symbols
            in: path
            required: true
            schema:
              type: array
              items:
                type: string
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    type: array
                    items:
                      \$ref: '#/components/schemas/Quote'
      /company/{name}:
        get:
          tags:
          - quote-v-1-controller
          operationId: getCompany
          parameters:
          - name: name
            in: path
            required: true
            schema:
              type: string
          responses:
            "200":
              description: OK
              content:
                '*/*':
                  schema:
                    \$ref: '#/components/schemas/CompanyInfo'
    components:
      schemas:
        Quote:
          type: object
          properties:
            symbol:
              type: string
            companyName:
              type: string
            currency:
              type: string
            latestPrice:
              type: number
            high:
              type: number
            low:
              type: number
            change:
              type: number
        CompanyInfo:
          type: object
          properties:
            symbol:
              type: string
            companyName:
              type: string
            exchange:
              type: string



# ---
# apiVersion: gateway.tsb.tetrate.io/v2
# kind: Group
# metadata:
#   tenant: $PREFIX-apps
#   organization: kubecon
#   workspace: marketdata
#   name: quotes-gw
# spec:
#   displayName: Quotes Gateway
#   description: Quotes Gateway
#   namespaceSelector:
#     names:
#       - "aws-east/$PREFIX-quotes"
#   configMode: BRIDGED
# ---
# kind: IngressGateway
# metadata:
#   name: app-gateway
#   group: quotes-gw
#   workspace: marketdata
#   tenant: $PREFIX-apps
#   organization: kubecon
# spec:
#   workloadSelector:
#     namespace: $PREFIX-quotes
#     labels:
#       app: $PREFIX-quotes-gateway
#   http:
#     - name: gateway
#       port: 443
#       tls:
#         mode: SIMPLE
#         secretName: quotes-cert
#       hostname: quotes-$PREFIX.kubecon.cx.tetrate.info
#       routing:
#         rules:
#           - route:
#               host: "$PREFIX-quotes/quotes-service.$PREFIX-quotes.svc.cluster.local"
#               port: 8080
#     - name: quotes-internal
#       port: 80
#       hostname: quotes.$PREFIX.mesh
#       routing:
#         rules:
#           - route:
#               host: "$PREFIX-quotes/quotes-service.$PREFIX-quotes.svc.cluster.local"
#               port: 8080