---
apiVersion: api.tsb.tetrate.io/v2
kind: Tenant
metadata:
  description: $PREFIX applications
  displayName: $PREFIX applications
  name: $PREFIX-apps
  organization: kubecon
spec:
  description: $PREFIX applications
  displayName: $PREFIX applications
# ---
# apiVersion: rbac.tsb.tetrate.io/v2
# kind: TenantAccessBindings
# metadata:
#   name: $PREFIX-workshop
#   organization: workshop
#   tenant: $PREFIX-workshop
# spec:
#   allow:
#   - role: rbac/admin
#     subjects:
#     - user: admin
#     - user: organizations/workshop/users/$AD_UID
---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  tenant: $PREFIX-apps
  organization: kubecon
  name: wealth-mgmt
spec:
  description: Wealth Mgmt
  displayName: Wealth Mgmt
  namespaceSelector:
    names:
      - "*/$PREFIX-app"
      - "*/$PREFIX-app-tier1"
      - "*/$PREFIX-security"
---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  tenant: $PREFIX-apps
  organization: kubecon
  name: marketdata
spec:
  description: Market Data Services
  displayName: Market Data Services
  namespaceSelector:
    names:
      - "*/$PREFIX-quotes"
---
apiversion: api.tsb.tetrate.io/v2
kind: Workspace
metadata:
  tenant: $PREFIX-apps
  organization: kubecon
  name: customer360
spec:
  description: Customer 360
  displayName: Customer 360
  namespaceSelector:
    names:
      - "*/$PREFIX-microservices"
      - "*/$PREFIX-microservices-tier1"
