---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster }}-elastic
  namespace: argocd
  labels:
    cluster: {{ .Values.cluster }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: elasticsearch
    name: {{ .Values.cluster }}
  project: default
  syncPolicy:
    automated: {}
    syncOptions: 
    - CreateNamespace=true
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '17.9.8'
    chart: elasticsearch
    helm:
      releaseName: elasticsearch
      values: |
{{ .Files.Get "values-elasticsearch.yaml" | indent 8 }}