---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster }}-keycloak
  namespace: argocd
  labels:
    cluster: {{ .Values.cluster }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: keycloak
    name: {{ .Values.cluster }}
  project: default
  syncPolicy:
    automated: {}
    syncOptions: 
    - CreateNamespace=true
  source:
    path: cd/apps/keycloak
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      releaseName: keycloak
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      parameters:
      - name: "password"
        value: {{ .Values.keycloak.adminPwd }}
      values: |
{{ .Files.Get "values-keycloak.yaml" | indent 8 }}
    