---
apiVersion: tsb.tetrate.io/v2
kind: Workspace
metadata:
  name: marketdata
  namespace: default
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: demo-apps
spec:
  description: Market Data Services
  displayName: Market Data Services
  namespaceSelector:
    names:
      - "aws-east/demo-quotes"