---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster }}-bookinfo-tier1
  namespace: argocd
  labels:
    cluster: {{ .Values.cluster }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bookinfo
    name: {{ .Values.cluster }}
  project: default
  syncPolicy:
    # automated: {}
    syncOptions: 
    - CreateNamespace=true
  source:
    path: cd/apps/bookinfo-tier1
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      releaseName: bookinfo
      values: |
{{ .Files.Get "values-bookinfo-tier1.yaml" | indent 8 }}  