---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-customer360
  name: demo-customer360
  namespace: trafficgenerator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: demo-customer360
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-customer360
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - "while true; do curl -v -k -H 'X-B3-Sampled: 1' https://customer360.gke-east.tetrate.cloud.zwickey.net/p/http/accounts-service/p/http/issues.demo.mesh/p/http/issues-backend; sleep 10; done"
        image: appropriate/curl
        imagePullPolicy: Always
        name: trafficgenerator
        resources:
          limits:
            cpu: 50m
            memory: 16Mi
          requests:
            cpu: 10m
            memory: 4Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always