---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: keycloak
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.domain }}
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - {{ .Values.domain }}
    secretName: keycloak-certs
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080