---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster }}-es-deployment
  namespace: argocd
  labels:
    cluster: {{ .Values.cluster }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: elastic-system
    name: {{ .Values.cluster }}
  project: tsb-1.5
  syncPolicy:
    automated: {}
    syncOptions: 
    - CreateNamespace=true
  source:
    path: cd/apps/elastic
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      releaseName: elastic
      values: |
{{ .Files.Get "values-es.yaml" | indent 8 }}  