---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster }}-postgres
  namespace: argocd
  labels:
    cluster: {{ .Values.cluster }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: postgres
    name: {{ .Values.cluster }}
  project: tsb-1.5
  syncPolicy:
    automated: {}
    syncOptions: 
    - CreateNamespace=true
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '11.6.6'
    chart: postgresql
    helm:
      releaseName: postgres
      values: |
{{ .Files.Get "values-postgres.yaml" | indent 8 }}