image:
  registry: gcr.io/abz-perm
  tag: 1.5.1
operator:
  deployment:
    env:
    - name: CONTROL_PLANE_REVISION
      value: tsb-1-5-0-stable
spec:
  components:
    gitops:
      enabled: true
      reconcileInterval: 60s
    internalCertProvider:
      certManager:
        managed: EXTERNAL
    xcp:
      revision: tsb-1-5-0-stable
      centralAuthMode: JWT
    rateLimitServer:
      backend:
        redis:
          uri: ratelimit-redis.default.svc.cluster.local:6379
    oap:
      kubeSpec:
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: oap-deployment
          patches:
          - path: spec.template.spec.containers.[name:oap].env[-1]
            value:
              name: SW_STREAMING_LOG_ENABLED
              value: "true"
  hub: gcr.io/abz-perm
  managementPlane:
    clusterName: tier1
    host: tsb.tetrate.cloud.zwickey.net
    port: 443
    selfSigned: false
  meshExpansion: {}
  telemetryStore:
    elastic:
      host: 35.236.205.203
      port: 9200
      protocol: https
      selfSigned: true
      version: 7
secrets:
  keep: false
  clusterServiceAccount:
    JWK: '{"alg":"RS256","d":"mUp6OJ7io8pQjeHCbmnKXe4AUp119P7xadjJoRBVB7CB3l6Js8_nOO823-UytS4DS3EBnqnJS2X23MXwpuEmj_4jSIvPnbRohy4yw9f8xOzPcXUQrl21lDQbU7CS9q4s1pIoYVf1nFPbttnz-rpKp9OTszqVoxxOR8f5ul5UVg4dkx-rtUsza0IqazejtFTByGBBuU93wh0HDGNDyfixTZs3Ys5m7dIfAOgmTMxn3P9uCUKyqVrYWv4NTwIFCJxYI0NkpIDuKBF8jJp7CTm5XLZjjLt6LdAoA5wU8hYl1nYR2Ab4ZDbo8OdAq2ivD2BS8M0rgzn_zT0gSQEpquQZjQ","dp":"EG1H4-lRTXDXczCDqkyt9PxS5RmlvXUygrVWrxpqr597KIfmy1jCstsJvDTewtZsFmWDpVPvg2NtUkjzZQs3zmyRbsQVJPAg5FFIj_3fyqXkUBhdgHWyRrA63KwgH-pUb099LUz-3vLi8n727ytTDSejC8XljzWGMcloS-K3VZc","dq":"iZi2dGBe_YJmgYNAJyAJyImFgsI7kH9OIG6ur3kkVrZhaRVuWhJbwe32bccwG4Jx8VzraFbFt5_gxgbP8sq7mbMnNtZKG9sVgE5o6PrF0GldF7GAvlAuL5IlkOQFNLsswLYbF1Eniq_ad-dGUFShY9VgZhEK1neMxl4feJfeLUk","e":"AQAB","kid":"c_GgcjjoJNB-S-vRJuQkjkT8Qoz8ESF7W0xaJttrmlk","kty":"RSA","n":"xgOE_5Y3Lz-3I6Z9Fj-H6G2Be-ta-TfInvmNyCw7cKAkZ68GYn4XH8vDv5ND9tH6uro02Stby2szLGb7f4rX2ytDqbY4gsSL0-70dd08wusL6h-1a3kYMb17ycmCJKsxPvjN7YDzbqrcquuvRSyypzMd67ebWrqNHK09rUdtXsjywKEu8t8l9pbHV4H5npmnRgQ7EOXxM8HiYE2iR8U0X72tscxrTQP7NcaHC99ICu5aiGBs-SDyjJNAtNDW3yxerJN3-vNPHaA_oBczJ8trNnwly-5XT-fJlm-rlKMpzo9a8zW63W7me0i-sR7TFdp8Y8-JcXCv9-6ffHOcsVQ8kQ","p":"yCSQ7aOiFqkvpD1vW4lpZsP67YMoRKxIhsZWKdauAAIJO8dtkdmMJEDA_8p09-sCFd-jnY8OMq7jenfq9r-l18ErzQ2PQR6YCBlccA2yQjvSZ-ELsw1olDoi-c_4Ml_eMTT-XzF07p4Aiq4pUQ_0OEl-C18zZ6kRVqWgNdPkaTM","q":"_UbWl55aPHcZQFm-5xDU5EUDDPgi4LM6PR9fKAFK-nf9sf4KSvSub7godvAFxYTT7-LBe6iNm1HiiKscvlu8RXonW-4s0yRG8tOwNo6WYmnhHlUimRJaXVwoZurnlmSdsdlB_M8vSBlYubE9dYJT3q-k2lzJ9HSP53WHp9CJKys","qi":"BkdoOeR_3yyW96YKoCvdat9tQi6Ao9TjCGsbjs9hQwgW_fGM_kRipWc0qcIPxd9WHJPe32_fTHrWRJfkqZGWJ3cDwK3EXpMBKNb9WATIRZpyg-DjbOZnPZ9Bf6sJHAC3K-CW2u3HFeV3iQ0eBxsPhBflxkZ4P7GB5Fz6eNuLvEE"}'
    clusterFQN: organizations/tetrate/clusters/tier1
  elasticsearch:
    cacert: |
      -----BEGIN CERTIFICATE-----
      MIIDujCCAqKgAwIBAgIQXuSO/8NcA6KX+VOtxSDfzTANBgkqhkiG9w0BAQsFADAh
      MQwwCgYDVQQLEwN0c2IxETAPBgNVBAMTCHRzYi1odHRwMB4XDTIyMDgxODE2NDEy
      OVoXDTIzMDgxODE2NTEyOVowPDEMMAoGA1UECxMDdHNiMSwwKgYDVQQDEyN0c2It
      a2ItaHR0cC5lbGFzdGljLXN5c3RlbS5rYi5sb2NhbDCCASIwDQYJKoZIhvcNAQEB
      BQADggEPADCCAQoCggEBAP3MipaenOKW9ea1ZHm5civtd86FxbD7zo6mn3xp5VRX
      D6c4vM3nVNr4BNUeXpRgKpnmmxsGfZie+Z2HMnY2praIi48ti9P9gqTZTVCHTksq
      yFNJd01N21qtd7m2NqOjH86bgFLjwuJwWb4JSFCamzdnPOMRw6KwunNGdcTfsPvF
      L7JdbeqEwPi8wJnODjmdmxbuTb81pFU5GpWVqY1zbOTCxULbC9+vdvJp0sx8AwCe
      pbnhPXh6+eTTtgTmGpJ+BfjMLnRyqKVAMojDrymqs//VmZ9Z2LrvRbVK1wopijIS
      LT7DzQtP2lrTs8QFjJ8wImRn6ihMJSjDfBP0laIvC2kCAwEAAaOB0jCBzzAOBgNV
      HQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB8GA1Ud
      IwQYMBaAFBWyaGuoMetWe4Hbbl+ItC4Wiqq5MH0GA1UdEQR2MHSCI3RzYi1rYi1o
      dHRwLmVsYXN0aWMtc3lzdGVtLmtiLmxvY2Fsggt0c2Ita2ItaHR0cIIedHNiLWti
      LWh0dHAuZWxhc3RpYy1zeXN0ZW0uc3Zjghp0c2Ita2ItaHR0cC5lbGFzdGljLXN5
      c3RlbYcEIlWiHTANBgkqhkiG9w0BAQsFAAOCAQEACelxPFRctra45ZU86048FjrM
      YpTxCWEN5d22EtB/XbbCWOJjg9zgdUEbpwyc0UkM6mFdlSJ9Q7oEIozGBtKqURTl
      0LTAwM8/GuKquvfxev/D0yn4k2A8mBDkyj1OhpaI+SN0iuqvO67CPkPYIh9CWwLo
      MCLsQ01Ty6dD6SYJL68gYTNUa/x4z5Yl7H3mkLo7sa/wTB5qGcYjloIScEGdweQx
      CVr8wNThXyIhqWVrNSWil0cjv8CG4aqMcU1Pl1shgG8hF7ROgmbjtq8KEnmwCMPr
      msu2Z/2dzLl3U1rWUo3I7sO0bKblczTt7vCpQs1fbY6GkDDH0d403g+UiY6o6g==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDLTCCAhWgAwIBAgIQTO0lFJ5iGhUBs7jDyGrpWDANBgkqhkiG9w0BAQsFADAh
      MQwwCgYDVQQLEwN0c2IxETAPBgNVBAMTCHRzYi1odHRwMB4XDTIyMDgxODE2NDA1
      MVoXDTIzMDgxODE2NTA1MVowITEMMAoGA1UECxMDdHNiMREwDwYDVQQDEwh0c2It
      aHR0cDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAO/otU/xiuQyDvRh
      vV+D+jSfc3zUoF0BlHK7Eus9lmR0Hlztn0VQgzC2/9aUFUCMizoL6j4cEV65WLMw
      GtL8++00TpQHjfj78MMxAZx5LLGJR8aru/lRKMD3TaYy7V3GP+lBUW2U5lml0eBr
      F2dQ9IS2SdpRFm8oFxGM1ZwQyk/vDg2we94TJOz9QAOpdjCiAxOy4Qi76aKNQW4r
      3v+2910/4KmynWYID/yAzOzPoRCJKuY9FnCxyLOIEsoMcbEfSSpfwMF+1/h3Aw5k
      L4ZGc2TEQ6TrWWHcTxsXw+JA+n3rb0kxeJPFhV1umUNw/7C3qxJhQ/u6EMFHdFzy
      4vb/7NUCAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKEMB0GA1UdJQQWMBQGCCsGAQUF
      BwMBBggrBgEFBQcDAjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQVsmhrqDHr
      VnuB225fiLQuFoqquTANBgkqhkiG9w0BAQsFAAOCAQEAHhHs9gCnk/hz+dbf2/tW
      qEr+pDh7gTABNKxnM8yKbxn+mnIYWM02rMdgI7OOo9yiwPrqlJpPngMT6SY4q/f/
      2gmr5lwe01Ps+H9FpCG0rRiLFGllL0RUQBWlztaJgQ+EpKXwCSa1V4OM1y7VPQZl
      J5qMA+zTEUiUaW6CflHPAKCsXdGV4nY6Tsmxs37/W11p6Le7uMl+nVE0wOYf3bFm
      AWS0RIdJpo06YprfjZ8ccvbyQmyF9wguFm/LUmh3nGEDjsOnG1e/Jnwc1tVNfl9C
      CbGjLSJuc7hX/NelS2amuzhYqRS/sjKVqkbsQcIrZs2xZUXYuuYLVejA1qKIheLy
      tA==
      -----END CERTIFICATE-----
    username: elastic
  tsb:
    cacert: |
      -----BEGIN CERTIFICATE-----
      MIIFOzCCBCOgAwIBAgISBHy/pDMLifxfxn29DHGwLc2PMA0GCSqGSIb3DQEBCwUA
      MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
      EwJSMzAeFw0yMjA1MDUxMjM0NDRaFw0yMjA4MDMxMjM0NDNaMCYxJDAiBgNVBAMM
      GyoudGV0cmF0ZS5jbG91ZC56d2lja2V5Lm5ldDCCASIwDQYJKoZIhvcNAQEBBQAD
      ggEPADCCAQoCggEBALhnFhmt8Ylcmgx7ohO4LE3VNW7t4h9HiBBzMel82w3C9sRX
      SII/JqYDBonJIzZf5jYtZC0P3/7ZXf+NAh34q/kW6hAfB3VYamXsUY9fxMAlb1xv
      cXxGGjB6k09Yh+imR/VMfymjlUTa5uh1g/49AwltySZWGB/RAzcBGpyzOfoHCx4i
      khAAUxpEJ5cqNEGvEhR4MnRFkmRHmp6bq2GJTy4BNx1yVc980MzDYQonFOs1eiYT
      JfsQi4Wih7x+pi7+kS05MIYUzWZ0CqmoOBp4kOZpxwKz9XtWRJDaIuUR4eS/ln7H
      qbi/lJ8WLw9VE70fUV6JtBdHBRavvtve/6DpP9ECAwEAAaOCAlUwggJRMA4GA1Ud
      DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
      AQH/BAIwADAdBgNVHQ4EFgQU+odXlGDQVyhKIP/Jd6/nbh7STl0wHwYDVR0jBBgw
      FoAUFC6zF7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUF
      BzABhhVodHRwOi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9y
      My5pLmxlbmNyLm9yZy8wJgYDVR0RBB8wHYIbKi50ZXRyYXRlLmNsb3VkLnp3aWNr
      ZXkubmV0MEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYI
      KwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBAwYKKwYBBAHW
      eQIEAgSB9ASB8QDvAHUARqVV63X6kSAwtaKJafTzfREsQXS+/Um4havy/HD+bUcA
      AAGAlG4WzQAABAMARjBEAiA2iDCifW4xwq/eNDhYH1HR8cC/CmH6AITTeb3U91/3
      GQIgCyzZ+uS3hWbBvtRlEod+jDm9sJcBEfHSQhorA+dvuNwAdgBvU3asMfAxGdiZ
      AKRRFf93FRwR2QLBACkGjbIImjfZEwAAAYCUbhgVAAAEAwBHMEUCIFh0sKPU3W1D
      eOew1dSk6cnfZH/tAJz3gTCCHE7LKPPcAiEAz5wc384sEGrIXpKaKByuvH9M6H5Q
      N4Rpd5Kbxj+tBwEwDQYJKoZIhvcNAQELBQADggEBAAqUOGE39jk8uohaOt7VM/9v
      nTVaQLXg2Y7ZWAqcPFiyfYlwSO1z+al4LZSnnFGRB7RtEY0EctC7PrWj6aBvAnYg
      HRNimq85rzm8MNDoqA3E9kSYkEt5EOA9Rc4RH3+XFBEnf5x3KYCLVvh2HF6xI1PX
      TN0NkQ/VLM3n0hxD4Q60ZKCv9n1dzrJwSpfI8vGWWbG+mQUgN6W60lYGchBnAs3j
      TpJezIX5GOrSFNodXrRvj0xwvvWGEsE9kZz+OiyGPWvhFhRkglnKRJoCk1iRELaa
      4EFznCp3vcMaxHBSX4i0H0YO/RWLG4gMrKrVW69brOhp+03UxN+F03g3MqvKZYU=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
      WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
      RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
      R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
      sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
      NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
      Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
      /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
      AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
      Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
      FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
      AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
      Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
      gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
      PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
      ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
      CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
      lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
      avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
      yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
      yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
      hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
      HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
      MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
      nLRbwHOoq7hHwg==
      -----END CERTIFICATE-----
  xcp:
    rootca: |
      -----BEGIN CERTIFICATE-----
      MIIDKjCCAhKgAwIBAgIQP7a07wBIPpXK/cmmSmUxkTANBgkqhkiG9w0BAQsFADAv
      MRUwEwYDVQQKEwxjZXJ0LW1hbmFnZXIxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2Ew
      HhcNMjIwNTMxMDAwMjQzWhcNMjQxMTE2MDAwMjQzWjAvMRUwEwYDVQQKEwxjZXJ0
      LW1hbmFnZXIxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2EwggEiMA0GCSqGSIb3DQEB
      AQUAA4IBDwAwggEKAoIBAQC9uZZC/U9WetgSCt+HbDE6VmcyDVbpXxrJI/ZFUqD7
      ZTpicSnYAYofB4bVH5Ba+Y95ZPijs96RjpNmEPqs5kFT+6NxyhAjJTc5qrVBdASp
      x9C/xMOc1VwRBegx/7a9xJoBqRizRtUJrDo297wWgUhTsjVp5OVDUsRt9dgUlrvG
      2pq0kxdwamkdT5BEq9TPoOMVmEWwXGmQV6g95mBw8/VnfcO1pv7yz3kQxNzny3Bd
      ZhdVFhW5El54SiEKI1FzDM1prJFD4yeBPZ4bUqNfChjbujHniyfj4myxfMZFvb2o
      WWl5Qb983BA/khBBkxgzoNgtvBIY+9Zpq2Zhxtpa7EXRAgMBAAGjQjBAMA4GA1Ud
      DwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQuHUUghfaF+bG9
      39hWJF1de7klnzANBgkqhkiG9w0BAQsFAAOCAQEADn0jZrPAbJqdA4O8cKryITRd
      PKy+8+8E1x1765Jw+HqRHb0K+x54GnIMKDlDcexpZkrcRR7pkkeQ4Sx9MPIFSnd3
      BezfTjOcBfIzB3gj0pMbfL2kViHhEv5qM576ScJrgNHqFhHe8wCpoxP+vNDzI7jt
      wUy5zaH5h9JBXPwo6j/TSPSiUjt00d083+ACzRlWNJXYVngwOtb/t23MZ6prV/8h
      4BFF0GlpwM+1EGlOERjKgBTc+Ir9v1HZZCVtgal0aAGczFTxvOBghu7Nwfz5e5IG
      TLKxAFhox3XbRep+1d/tn6yHqU5Yp6VUEzyLZ48CZ6gDEqM7wrCLBoKJ+SchvQ==
      -----END CERTIFICATE-----