image:
  registry: gcr.io/abz-perm
  tag: 1.5.0-EA3
spec:
  components:
    gitops:
      enabled: true
      reconcileInterval: 60s
    internalCertProvider:
      certManager:
        managed: EXTERNAL
    xcp:
      centralAuthMode: JWT
    rateLimitServer:
      backend:
        redis:
          uri: ratelimit-redis.default.svc.cluster.local:6379
  hub: gcr.io/abz-perm
  managementPlane:
    clusterName: tier1
    host: tsb.tetrate.cloud.zwickey.net
    port: 443
    selfSigned: false
  meshExpansion: {}
  telemetryStore:
    elastic:
      host: 34.85.219.28
      port: 9200
      protocol: https
      selfSigned: true
      version: 7
secrets:
  keep: false
  clusterServiceAccount:
    JWK: '{"alg":"RS256","d":"7AG3IewA7YFHQvkWbLtaDzWyJapJjghkEbGscJKje8JlcVjRFX__X19vwM_8FxVkwkQx8-pfkotvrpEl-J3omupteUaFGyM1gPbOs5OnYGZRrJbkCmqyrboN7dlPhWAxLWPMiaYFn0Ekul1hV2R0VXTCC1gS01xdQWpJCKfTQtCBO59lrJsfBVeajwuhk3i6IBILFz01zVayG8X7FLbZ5N4-23Z3KMeXXfWcZeyVJW0mUmMVuA_gi4cVRew6n0Qfjgma7xSKEI_F_1HJzh7cxTPTSV8bZSFgSn8xgUEYNMBLLDti22P2IH1tUqQ2COyhVtw4l11lthCz20bzZ73t4Q","dp":"BYvKdI2pswNdshvG1qkNH4LZ8bHOV2H-uUXnnWmn8ay8GA87ANfDamLf1AbwKNl1zykBwhkeQDbqlJDP5TeynSW1wSqkZ5F95lrC5melUiSJ9sfme63Jll2zcE_BhRn0ucAiNrG4ipshDMy07QpxJ4Mg5JvVa0a-vsTXOrkt44k","dq":"wJSmxpYTBWyY993aObY1E71knts2VliHDKBcZKar7sUXt0VnKuZu0CV_yCRYe2DesZtIKGJFI_WSKY3fs9a6gb-RsUeVI7DumrdQG8aW9UqdVOebRV_6ouSkiUulyN2Q8H_GQu3jEPllcymtW5GL9QQD9x9ErtIgJyryc-MBmQE","e":"AQAB","kid":"bbMS8ZYRdyNfbrQnissIwGx8rrLbs202RLvzR1D4UMs","kty":"RSA","n":"7pdsgypnSZDzNdRuvIHabH469KP5Wefxedw9F3EAA29ktalghqX-mX3o1hivRHoiGBWoMvFqF77FkzF8l9RgZ9KSk6brrFytUCtXtEioLdSf8eF2DUFzXO0YTDJElqTtUttztOaR1y-7LOVzLMC9hs90DIC-u6z2pN4lsVT8SVzbJ8GwhO5fcVQ6YItjNFexYi-RCS7TE0g9ItRVdaiRpIs5WIo8yqlJH-VMmMpY9fkFJCCI3Tujj6U3O4yOk7HVwOzUWuqBwzmUfKHNNil2yauCVarmP_JEdh1sceVNdOKRKqyYEGsbklw8IDVqPT3TpYUahsrBYSv-KIqdjKlw_Q","p":"9-88evTePadqFIN7tfCYXv3PM0vLHyRXL0Ipym__L0RpnLH0I2h4hGqPACJCUgHcfCBKlUhbCaIwzfOB7RHIRIJtd9ymoPxqJSLLd4nn3WZZSgRpZmCdMGviUOKiM5jw7labj4e5gjZsQURnrt0b7pY_hH4Vf4E54_zbQK67UpU","q":"9lphWvenO6QMp4eGl_y3S5Cr37MIuOszMZsl694vHiVy8zGPq_XlFvea2fbjiVIotPoNcy4eaYHzCzF0k2FKedByaakL45FwyaneMlJxMEw0ms7U5FBFF1eAoRmozAyZ5OaHm9flIY-zylljAR0jsMT2OMfap16TZPPQ0tsCssk","qi":"OZvRIBe7kLv2ZVMHE2FbkI-0ROzzktb18IXcGyAqJjgu_x65WTpX_JJY86tzlQlcYqvij3EFpB8rLs-lL8tOjp_KcPgb0nhuNbeu93CfB0Y1OQTUXiW5vVEkXfKye3aRL65MvGqbPpxGJiSgUP1SOqR1SxvM3Ez161ys2VcWunc"}'
    clusterFQN: organizations/tetrate/clusters/tier1
  elasticsearch:
    cacert: |
      -----BEGIN CERTIFICATE-----
      MIIDLjCCAhagAwIBAgIRAL4TcaQ9cGjH2XIKnj+M6LQwDQYJKoZIhvcNAQELBQAw
      ITEMMAoGA1UECxMDdHNiMREwDwYDVQQDEwh0c2ItaHR0cDAeFw0yMjA2MTMyMDIx
      MzhaFw0yMzA2MTMyMDMxMzhaMCExDDAKBgNVBAsTA3RzYjERMA8GA1UEAxMIdHNi
      LWh0dHAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC4/QS7x8YrqAf3
      aSuBoPM0N1kFOubFWhhnOX3Gpl8BMZxLrmivnul4jGWWd69F5KQ19q8115HoYgbZ
      3w8uKJRvb4uCeDzmJ7olVj5Olz5NO/P6sxBHksvzuaw+nP1v+9Tbdk5mfLW5qhQU
      NsRNtgH12aozf4SpNxSzrh3zJgG/3uhA9nMBzVXyD0ru6/PfN6OKKJ+4ce4YSSpF
      s7dBCW1LdOOKoGbNIDA/e4Ewah7vdJ4HAKCXxuveqxYmErCS88UGJCr/6KiLwbOM
      BZvbQYMXC9fgNk2Rpih+JiYVB5rCMSe1/Q4PA5PXm4BVW7xAGVx4bMvMYm2cvNc6
      KhpD13nLAgMBAAGjYTBfMA4GA1UdDwEB/wQEAwIChDAdBgNVHSUEFjAUBggrBgEF
      BQcDAQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUMUrO9ny+
      VMmDYzxmzuilQ6TEAmMwDQYJKoZIhvcNAQELBQADggEBACLoUPN81r1pP43HgpPR
      UiT2nYhHF8+VJzkYmwdzl7mX5A0zyQamXZguABHKfnraAkzsPc8WoeE1qcWtXgf2
      TppkiImANK5ZEKUo1xaURq3QhdOJFjDOH0SfVoCDmaAE/p4iFjQ6n9DCKesydJQs
      cUo52h5A+taliEo6sQh9nXjjBwuYolmEl1mg9KegVbWvdDu9BY57SojtdOyknDKz
      FwjnduRkjNXB/lAHDHnc2HWoIbqgZ9uebkDc4f/ohH0LtwqLSVqyhEsHRvcFnHPV
      mXch9ktOmny9/jO//Y8ef3SPxwXmgsQDkLzuZGGAGbzTgy04hmWupE+pPD7X3yXg
      4l0=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIEMjCCAxqgAwIBAgIQIxKUmN/EcI61TYyz20enQTANBgkqhkiG9w0BAQsFADAh
      MQwwCgYDVQQLEwN0c2IxETAPBgNVBAMTCHRzYi1odHRwMB4XDTIyMDYxMzIwMjIy
      N1oXDTIzMDYxMzIwMzIyN1owPDEMMAoGA1UECxMDdHNiMSwwKgYDVQQDEyN0c2It
      ZXMtaHR0cC5lbGFzdGljLXN5c3RlbS5lcy5sb2NhbDCCASIwDQYJKoZIhvcNAQEB
      BQADggEPADCCAQoCggEBAK+fIsOZGgE7lsbNIvnx2o+xP63cdJquAHufA6YMHiyc
      hQ2ImvWqGCfUCoaS7VbxWPK+gOhmZcRppsjTbQzkIPBksy6dLflq+uxVFuwh7FMB
      HG0zDox+1hv1OcF8Jhx3Ndpb2GDZ8OqzCT/ApoBah6tei7zVWrfSZjIuku6zXfpS
      PzuW/E1AAcjK2tsoNq9Ffm372Zy7wq+qStRDR6RK9WAQC6PzBw0r+ApFiERMJ0qR
      tBkMTLWiAjpmHmNwLxWjB8MwkMaUycxU2ENeVSz349AjAQ9/IseczuhOhjhhcFiX
      2j+9H3WFsMhB4bdbDYVp+YGriyZo3raaXKUEzZQseFkCAwEAAaOCAUkwggFFMA4G
      A1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHwYD
      VR0jBBgwFoAUMUrO9ny+VMmDYzxmzuilQ6TEAmMwgfIGA1UdEQSB6jCB54IjdHNi
      LWVzLWh0dHAuZWxhc3RpYy1zeXN0ZW0uZXMubG9jYWyCC3RzYi1lcy1odHRwgh50
      c2ItZXMtaHR0cC5lbGFzdGljLXN5c3RlbS5zdmOCGnRzYi1lcy1odHRwLmVsYXN0
      aWMtc3lzdGVtgid0c2ItZXMtaW50ZXJuYWwtaHR0cC5lbGFzdGljLXN5c3RlbS5z
      dmOCI3RzYi1lcy1pbnRlcm5hbC1odHRwLmVsYXN0aWMtc3lzdGVtgiMqLnRzYi1l
      cy1kZWZhdWx0LmVsYXN0aWMtc3lzdGVtLnN2Y4cEIlXbHDANBgkqhkiG9w0BAQsF
      AAOCAQEACMVVSrE86+vwZSySIig15Ew4DsP3WYH3awAeV5vYElDltSJa5KTCMIpJ
      88J5/WrxCpFEJE6oAWDhPuUce3ZzraYuWjAIWHXJY4iUL8V6DZBQC4K5qNUgVmqc
      HjDWdBFgxvGLYhrqi4Z0v4N50/k0PwKrWgeIEyWFzZrPl9QXb8huldUtyedvAYgJ
      T7rQhtewiFfg1+L996Prt9fCQZzZvuVDCzLOJNGlh0DBd/QAGLsqBvhokjU7VCdq
      ZFOo2v0dEzZRkOlLXhLXQWPc3pqszurzsQr7qPjifk1JGEWFM7Jxb9NUg1hngat6
      cUKUE9556yDMnlpHaGZvI95/Fsu0lA==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDLjCCAhagAwIBAgIRAL4TcaQ9cGjH2XIKnj+M6LQwDQYJKoZIhvcNAQELBQAw
      ITEMMAoGA1UECxMDdHNiMREwDwYDVQQDEwh0c2ItaHR0cDAeFw0yMjA2MTMyMDIx
      MzhaFw0yMzA2MTMyMDMxMzhaMCExDDAKBgNVBAsTA3RzYjERMA8GA1UEAxMIdHNi
      LWh0dHAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC4/QS7x8YrqAf3
      aSuBoPM0N1kFOubFWhhnOX3Gpl8BMZxLrmivnul4jGWWd69F5KQ19q8115HoYgbZ
      3w8uKJRvb4uCeDzmJ7olVj5Olz5NO/P6sxBHksvzuaw+nP1v+9Tbdk5mfLW5qhQU
      NsRNtgH12aozf4SpNxSzrh3zJgG/3uhA9nMBzVXyD0ru6/PfN6OKKJ+4ce4YSSpF
      s7dBCW1LdOOKoGbNIDA/e4Ewah7vdJ4HAKCXxuveqxYmErCS88UGJCr/6KiLwbOM
      BZvbQYMXC9fgNk2Rpih+JiYVB5rCMSe1/Q4PA5PXm4BVW7xAGVx4bMvMYm2cvNc6
      KhpD13nLAgMBAAGjYTBfMA4GA1UdDwEB/wQEAwIChDAdBgNVHSUEFjAUBggrBgEF
      BQcDAQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUMUrO9ny+
      VMmDYzxmzuilQ6TEAmMwDQYJKoZIhvcNAQELBQADggEBACLoUPN81r1pP43HgpPR
      UiT2nYhHF8+VJzkYmwdzl7mX5A0zyQamXZguABHKfnraAkzsPc8WoeE1qcWtXgf2
      TppkiImANK5ZEKUo1xaURq3QhdOJFjDOH0SfVoCDmaAE/p4iFjQ6n9DCKesydJQs
      cUo52h5A+taliEo6sQh9nXjjBwuYolmEl1mg9KegVbWvdDu9BY57SojtdOyknDKz
      FwjnduRkjNXB/lAHDHnc2HWoIbqgZ9uebkDc4f/ohH0LtwqLSVqyhEsHRvcFnHPV
      mXch9ktOmny9/jO//Y8ef3SPxwXmgsQDkLzuZGGAGbzTgy04hmWupE+pPD7X3yXg
      4l0=
      -----END CERTIFICATE-----
    username: elastic
  tsb:
    cacert: |
      -----BEGIN CERTIFICATE-----
      MIIFOzCCBCOgAwIBAgISBHy/pDMLifxfxn29DHGwLc2PMA0GCSqGSIb3DQEBCwUA
      MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
      EwJSMzAeFw0yMjA1MDUxMjM0NDRaFw0yMjA4MDMxMjM0NDNaMCYxJDAiBgNVBAMM
      GyoudGV0cmF0ZS5jbG91ZC56d2lja2V5Lm5ldDCCASIwDQYJKoZIhvcNAQEBBQAD
      ggEPADCCAQoCggEBALhnFhmt8Ylcmgx7ohO4LE3VNW7t4h9HiBBzMel82w3C9sRX
      SII/JqYDBonJIzZf5jYtZC0P3/7ZXf+NAh34q/kW6hAfB3VYamXsUY9fxMAlb1xv
      cXxGGjB6k09Yh+imR/VMfymjlUTa5uh1g/49AwltySZWGB/RAzcBGpyzOfoHCx4i
      khAAUxpEJ5cqNEGvEhR4MnRFkmRHmp6bq2GJTy4BNx1yVc980MzDYQonFOs1eiYT
      JfsQi4Wih7x+pi7+kS05MIYUzWZ0CqmoOBp4kOZpxwKz9XtWRJDaIuUR4eS/ln7H
      qbi/lJ8WLw9VE70fUV6JtBdHBRavvtve/6DpP9ECAwEAAaOCAlUwggJRMA4GA1Ud
      DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
      AQH/BAIwADAdBgNVHQ4EFgQU+odXlGDQVyhKIP/Jd6/nbh7STl0wHwYDVR0jBBgw
      FoAUFC6zF7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUF
      BzABhhVodHRwOi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9y
      My5pLmxlbmNyLm9yZy8wJgYDVR0RBB8wHYIbKi50ZXRyYXRlLmNsb3VkLnp3aWNr
      ZXkubmV0MEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYI
      KwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBAwYKKwYBBAHW
      eQIEAgSB9ASB8QDvAHUARqVV63X6kSAwtaKJafTzfREsQXS+/Um4havy/HD+bUcA
      AAGAlG4WzQAABAMARjBEAiA2iDCifW4xwq/eNDhYH1HR8cC/CmH6AITTeb3U91/3
      GQIgCyzZ+uS3hWbBvtRlEod+jDm9sJcBEfHSQhorA+dvuNwAdgBvU3asMfAxGdiZ
      AKRRFf93FRwR2QLBACkGjbIImjfZEwAAAYCUbhgVAAAEAwBHMEUCIFh0sKPU3W1D
      eOew1dSk6cnfZH/tAJz3gTCCHE7LKPPcAiEAz5wc384sEGrIXpKaKByuvH9M6H5Q
      N4Rpd5Kbxj+tBwEwDQYJKoZIhvcNAQELBQADggEBAAqUOGE39jk8uohaOt7VM/9v
      nTVaQLXg2Y7ZWAqcPFiyfYlwSO1z+al4LZSnnFGRB7RtEY0EctC7PrWj6aBvAnYg
      HRNimq85rzm8MNDoqA3E9kSYkEt5EOA9Rc4RH3+XFBEnf5x3KYCLVvh2HF6xI1PX
      TN0NkQ/VLM3n0hxD4Q60ZKCv9n1dzrJwSpfI8vGWWbG+mQUgN6W60lYGchBnAs3j
      TpJezIX5GOrSFNodXrRvj0xwvvWGEsE9kZz+OiyGPWvhFhRkglnKRJoCk1iRELaa
      4EFznCp3vcMaxHBSX4i0H0YO/RWLG4gMrKrVW69brOhp+03UxN+F03g3MqvKZYU=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
      WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
      RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
      R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
      sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
      NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
      Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
      /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
      AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
      Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
      FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
      AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
      Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
      gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
      PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
      ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
      CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
      lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
      avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
      yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
      yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
      hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
      HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
      MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
      nLRbwHOoq7hHwg==
      -----END CERTIFICATE-----
  xcp:
    rootca: |
      -----BEGIN CERTIFICATE-----
      MIIDKjCCAhKgAwIBAgIQP7a07wBIPpXK/cmmSmUxkTANBgkqhkiG9w0BAQsFADAv
      MRUwEwYDVQQKEwxjZXJ0LW1hbmFnZXIxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2Ew
      HhcNMjIwNTMxMDAwMjQzWhcNMjQxMTE2MDAwMjQzWjAvMRUwEwYDVQQKEwxjZXJ0
      LW1hbmFnZXIxFjAUBgNVBAMTDXNlbGZzaWduZWQtY2EwggEiMA0GCSqGSIb3DQEB
      AQUAA4IBDwAwggEKAoIBAQC9uZZC/U9WetgSCt+HbDE6VmcyDVbpXxrJI/ZFUqD7
      ZTpicSnYAYofB4bVH5Ba+Y95ZPijs96RjpNmEPqs5kFT+6NxyhAjJTc5qrVBdASp
      x9C/xMOc1VwRBegx/7a9xJoBqRizRtUJrDo297wWgUhTsjVp5OVDUsRt9dgUlrvG
      2pq0kxdwamkdT5BEq9TPoOMVmEWwXGmQV6g95mBw8/VnfcO1pv7yz3kQxNzny3Bd
      ZhdVFhW5El54SiEKI1FzDM1prJFD4yeBPZ4bUqNfChjbujHniyfj4myxfMZFvb2o
      WWl5Qb983BA/khBBkxgzoNgtvBIY+9Zpq2Zhxtpa7EXRAgMBAAGjQjBAMA4GA1Ud
      DwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQuHUUghfaF+bG9
      39hWJF1de7klnzANBgkqhkiG9w0BAQsFAAOCAQEADn0jZrPAbJqdA4O8cKryITRd
      PKy+8+8E1x1765Jw+HqRHb0K+x54GnIMKDlDcexpZkrcRR7pkkeQ4Sx9MPIFSnd3
      BezfTjOcBfIzB3gj0pMbfL2kViHhEv5qM576ScJrgNHqFhHe8wCpoxP+vNDzI7jt
      wUy5zaH5h9JBXPwo6j/TSPSiUjt00d083+ACzRlWNJXYVngwOtb/t23MZ6prV/8h
      4BFF0GlpwM+1EGlOERjKgBTc+Ir9v1HZZCVtgal0aAGczFTxvOBghu7Nwfz5e5IG
      TLKxAFhox3XbRep+1d/tn6yHqU5Yp6VUEzyLZ48CZ6gDEqM7wrCLBoKJ+SchvQ==
      -----END CERTIFICATE-----